explore-siargao/es-main

- apps/api/src/routes/api/rentals-v2/index.ts
- apps/api/src/routes/api/rentals-v2/services/rates.ts
- pnpm-lock.yaml
> [Story-Feature] Added get rental rates endpoints

- apps/api/src/common/helpers/prismaClient.ts
- apps/api/src/routes/api/rentals-v2/index.ts
- apps/api/src/routes/api/rentals-v2/services/default.ts
- apps/api/src/routes/api/rentals-v2/services/rates.ts
- packages/database/mongo/models/dbRentalRates.ts
- pnpm-lock.yaml
> [Story-Feature] Created update rental rates endpoint

- apps/api/src/routes/api/rentals-v2/index.ts
- apps/api/src/routes/api/rentals-v2/services/photos.ts
> [Task-Story] update rental photos endpoint

- apps/api/src/routes/api/rentals-v2/index.ts
- apps/api/src/routes/api/rentals-v2/services/photos.ts
> [Task-Story] Story edit photo info endpoint

- apps/api/src/common/helpers/prismaClient.ts
- apps/api/src/routes/api/rentals-v2/index.ts
- apps/api/src/routes/api/rentals-v2/services/default.ts
- apps/api/src/routes/api/rentals-v2/services/photos.ts
- apps/api/src/routes/api/rentals-v2/services/rates.ts
- packages/database/mongo/models/dbRentals.ts
> [Story-Feature] Added delete rental photo endpoint

- apps/api/src/routes/api/rentals-v2/index.ts
- apps/api/src/routes/api/rentals-v2/services/locations.ts
Created  api v2 endpoint for get rental location
> [Story-Feature] Added get rental location v2 endpoint

- apps/api/src/routes/api/rentals-v2/index.ts
- apps/api/src/routes/api/rentals-v2/services/basicInfo.ts
- apps/api/src/routes/api/rentals-v2/services/details.ts
- apps/api/src/routes/api/rentals-v2/services/finishedSections.ts
- apps/api/src/routes/api/rentals-v2/services/photos.ts
- apps/api/src/routes/api/rentals-v2/services/rates.ts
- packages/database/mongo/models/dbRentals.ts
Created api v2 endpoint fo get finished section.
> [Story-Feature] Added api v2 get finished section endpoint

- apps/api/src/routes/api/rentals-v2/index.ts
- apps/api/src/routes/api/rentals-v2/services/locations.ts
- packages/contract/src/Rental/type.ts
- packages/contract/src/Rental/zod.ts
Added update Rental Location endpoint
> [Story-Feature] Added update Rental Location endpoint

- apps/api/src/routes/api/rentals-v2/index.ts
- apps/api/src/routes/api/rentals-v2/services/addOns.ts
- packages/contract/src/Rental/zod.ts
Added get addons endpoints for mongoDB.
> [Story-Feature] Added get addons endpoint

- apps/api/src/routes/api/rentals-v2/index.ts
- apps/api/src/routes/mock/rentals/middleware/isHostRentalOwner2.ts
Created isHostRentalOwner2 middleware and apply it to index.ts
> [Story-Feature] Created isHostRentalOwner2 middleware and apply it to index.ts

- apps/api/src/routes/api/rentals-v2/index.ts
- apps/api/src/routes/api/rentals-v2/services/addOns.ts
Added update addons endpoint for mongoDB.
> [Story-Feature] Added update addons endpoint

- apps/web/module/Authentication/hooks/useLogin2.ts
- apps/web/module/Authentication/hooks/useRegister2.ts
Implemented login and register backend api v2 to frontend
> [Story-Feature] Implemented api v2 to login ang register manual

- apps/web/module/AccountSettings/hooks/useAddEmergencyContact.ts
Add Emergency Contact v2 hook implementation.
> [Story-Feature] Add Emergency Contact

- apps/web/module/AccountSettings/hooks/useUpdatePersonalInfo.ts
Modified useUpdatePersonalInfo hook to v2. Needs testing.
> [Story-Feature] story update personal info

- apps/web/module/AccountSettings/hooks/useRemoveEmergencyContact.ts
Remove EmergencyContact v2 hook implementation
> [Story-Feature] Remove EmergencyContact

- apps/web/common/hooks/useGetSessionUser.ts
Implemented get session api v2 in frontend hook
> [Story-Feature] Implmented get session api v2 in frontend

- apps/web/module/AccountSettings/hooks/useAddGovernmentId.ts
Modified useAddGovernmentId hook v2. Needs testing.
> [Story-Feature] Modified useAddGovernmentId 

- apps/web/module/Authentication/hooks/useGoogleLogin.ts
- apps/web/module/Authentication/hooks/useGoogleRedirect.ts
Implemented google login and register api v2 to frontend hook
> [Story-Feature] Implemented google login and register v2 in frontend

- apps/web/module/Authentication/hooks/useLogout.ts
Implemented logout api v2 to frontend hooks
> [Story-Feature] Implemented logout api v2 to frontend

- apps/api/src/common/middleware/auth/isCsrfTokenValid3.ts
- apps/api/src/routes/api/users-v2/index.ts
- apps/api/src/routes/api/users-v2/services/auth.ts
- apps/web/module/Authentication/hooks/useForgotPassword.ts
Implemented forgot password api v2 to frontend
> [Story - Feature] Implemented forgot password api v2 to frontend

- apps/web/module/AccountSettings/hooks/useUpdateUserEmail.ts
Implemented update user email api v2 to frontend hook
> [Story-Feature] Implemented update email api v2 to frontend

- apps/web/module/AccountSettings/LoginSecurity/DeactivateAccount.tsx
- apps/web/module/AccountSettings/components/modals/DeactivateUserModal.tsx
- apps/web/module/AccountSettings/hooks/useDeactivateAccount.ts
Implemented deactivate account in frontend hook
> [Story-Feature] Implemented deactivate account api v2 to frontend

- apps/api/src/routes/api/users-v2/services/personalInfo.ts
- apps/web/common/types/global.ts
- apps/web/module/AccountSettings/PersonalInfo/LegalName.tsx
- apps/web/module/AccountSettings/PersonalInfo/PhoneNumber.tsx
- apps/web/module/AccountSettings/PersonalInfo/index.tsx
- apps/web/module/AccountSettings/hooks/useUpdatePersonalInfo.ts
- apps/web/module/LandingPage/hooks/useChangeToHost.ts
Modified Be a Host hook to v2. Already tested the hooks that was modified in earlier tasks:
update personal info 
useAddGovernmentId 
useChangeToHost
> [Story-Feature] Modified Be a Host hook to v2

- apps/web/module/Authentication/hooks/useSetReceivedEmail.ts
Implementation of setting can received email api v2 to frontend hook
> [Story - Feature] Implemented can received email api v2 to frontend

- apps/api/src/routes/api/users-v2/services/userProfile.ts
- apps/web/module/Profile/hooks/useGetProfile.ts
Implemented get profile api v2 to frontend hook
> [Story-Feature] Implemented get profile api v2 to frontend

- apps/web/module/AccountSettings/hooks/useUpdateLanguage.ts
Modified useUpdateLanguage hook to v2.
> [Story-Feature] Modified useUpdateLanguage hook to v2

- apps/api/src/routes/api/users-v2/services/userProfile.ts
- apps/web/module/Profile/hooks/useUpdateProfile.ts
Implemented update profile api v2 to frontend hook
> [Story-Feature] Implemented update profile api v2 to frontend

- apps/web/module/Accommodation/Checkout/PaymentOptions.tsx
- apps/web/module/Accommodation/Checkout/index.tsx
- apps/web/module/AccountSettings/PaymentPayout/Payments.tsx
- apps/web/module/AccountSettings/hooks/useGetPaymentMethods.ts
Modified useGetPaymentMethod hook to v2. Also modified files that caused an error during build, i replaced id as number to string type. The following modified files are:
PaymentOption.tsx
Payment.tsx
Checkout/index.tsx
this useGetPaymentMethod.ts is not yet tested.
> [Story-Feature] Modified useGetPaymentMethod hook to v2

- apps/api/src/common/middleware/auth/isUserLoggedIn3.ts
- apps/api/src/routes/api/users-v2/index.ts
- apps/api/src/routes/api/users-v2/services/personalInfo.ts
- apps/web/common/types/global.ts
- apps/web/module/AccountSettings/PersonalInfo/Address.tsx
- apps/web/module/AccountSettings/PersonalInfo/EmergencyContact.tsx
- apps/web/module/AccountSettings/PersonalInfo/index.tsx
- apps/web/module/AccountSettings/hooks/useAddAddress.ts
- apps/web/module/AccountSettings/hooks/useAddEmergencyContact.ts
- apps/web/module/AccountSettings/hooks/useRemoveEmergencyContact.ts
- packages/contract/src/Address/zod.ts
- packages/contract/src/EmergencyContact/zod.ts
- packages/contract/src/PersonalInfo/zod.ts
- packages/database/mongo/models/dbEmergencyContacts.ts
Add address, Add EmergencyContacts, Remove EmergencyContact v2 hook implementation
> [Story-Feature] Add Address

- apps/web/module/AccountSettings/PaymentPayout/Payments.tsx
- apps/web/module/AccountSettings/components/modals/AddCardDetailModal.tsx
- apps/web/module/AccountSettings/hooks/useAddPaymentMethod.ts
Modified useAddPaymentMethod hook to v2. Also modified some files that errored in build process:
AddCardDetailModal.tsx
PaymentPayout/Payments.tsx
This is not yet tested.
> [Story-Feature] Modified useAddPaymentMethod hook to v2

- apps/api/src/routes/api/payments-v2/index.ts
- apps/api/src/routes/api/payments-v2/services/coupons.ts
- apps/web/module/AccountSettings/PaymentPayout/Payments.tsx
- apps/web/module/AccountSettings/hooks/useUpdateCoupon.ts
Update coupons v2 hook implementation
> [Story-Feature] Update Coupons

- apps/api/src/routes/api/payments-v2/index.ts
- apps/api/src/routes/api/payments-v2/services/paymentMethods.ts
- apps/web/common/types/global.ts
- apps/web/module/Accommodation/Checkout/PaymentOptions.tsx
- apps/web/module/Accommodation/Checkout/index.tsx
- apps/web/module/AccountSettings/PaymentPayout/Payments.tsx
- apps/web/module/AccountSettings/components/modals/RemovePaymentModal.tsx
- apps/web/module/AccountSettings/hooks/useGetPaymentMethods.ts
- apps/web/module/AccountSettings/hooks/useRemovePaymentMethod.ts
- apps/web/module/AccountSettings/hooks/useUpdatePaymentMethod.ts
Modified useUpdatePaymentMethod hook to v2. Modified files with errors after building:
accomodation/index.tsx
Checkout/PaymentOptions.tsx
removed session.od parameter in states.
> [Story-Feature] Modified useUpdatePaymentMethod hook to v2

- apps/web/module/AccountSettings/Taxes/Taxpayers.tsx
- apps/web/module/Listing/hooks/useGetTaxByUser.ts
Implemented get tax by user api v2 in frontend hooks
> [Story-Feature] Implemented get tax by user api v2 to frontend

- apps/web/module/Listing/hooks/useAddTax.ts
> [Story-Feature] Implement add tax api v2

- apps/web/module/AccountSettings/Taxes/Taxpayers.tsx
- apps/web/module/Listing/hooks/useAddTax.ts
- apps/web/module/Listing/hooks/useGetTaxByUser.ts
Implemented tax rest api v2 and test it
> [Feature-Develop] Implemented tax rest api v2 and test it

- apps/web/module/Hosting/Listings/hooks/useAddBlankRental.ts
Add Blank Rental Pending v2 hook implementation
> [Story-Feature] Implement Add Blank Rental Pending

- apps/web/module/Hosting/Listings/Rentals/Rental/hooks/useGetRentalAddOns.ts
Modified useGetRentalAddOns hook to v2. Not tested yet.
> [Story-Feature] Modified useGetRentalAddOns hook to v2

- apps/web/module/Admin/Listings/Declined/Rental/hooks/useGetRentalLocation.ts
Get rental location v2 hook implementation
> [Story-Feature] Implement Get Rental locations api v2

- apps/web/module/Hosting/Listings/hooks/useGetRentalBasicInfo.ts
Added useGetRentalBasicInfo hook v2. This needs testing.
> [Story-Feature] Added useGetRentalBasicInfo hook v2

- apps/web/module/Hosting/Listings/Activities/Activity/Itinerary/index.tsx
- apps/web/module/Hosting/Listings/Rentals/Rental/Location/index.tsx
- apps/web/module/Hosting/Listings/Rentals/Rental/hooks/useUpdateRentalLocation.ts
Update rental location v2 hook implementation
> [Story-Feature] Implement Update Rental Location

- apps/api/src/routes/api/rentals-v2/services/default.ts
- apps/web/module/Admin/Listings/Declined/Rental/hooks/useGetAllRentals.ts
- apps/web/module/Admin/Listings/hooks/useGetHostRentals.ts
- apps/web/module/Hosting/Listings/Rentals/Rental/hooks/useGetAllRentals.ts
- apps/web/module/Hosting/Listings/Rentals/index.tsx
- apps/web/module/Hosting/Listings/hooks/useGetHostRentals.ts
Implemented api v2 to frontend
> [Story-feature] Implemented api v2 to frontend

- apps/web/module/Admin/Listings/Declined/Rental/AddOns/index.tsx
- apps/web/module/Admin/Listings/Declined/Rental/BasicInfo/index.tsx
- apps/web/module/Admin/Listings/Declined/Rental/Details/index.tsx
- apps/web/module/Admin/Listings/Declined/Rental/Location/index.tsx
- apps/web/module/Admin/Listings/Declined/Rental/Photos/index.tsx
- apps/web/module/Admin/Listings/Declined/Rental/Pricing/index.tsx
- apps/web/module/Admin/Listings/Declined/Rental/Summary/index.tsx
- apps/web/module/Admin/Listings/Declined/Rental/hooks/useUpdateRentalAddOns.ts
- apps/web/module/Admin/Listings/Declined/Rental/hooks/useUpdateRentalDetails.ts
- apps/web/module/Admin/Listings/Declined/Rental/hooks/useUpdateRentalLocation.ts
- apps/web/module/Admin/Listings/Declined/Rental/hooks/useUpdateRentalPhotos.ts
- apps/web/module/Admin/Listings/Declined/Rental/hooks/useUpdateRentalPricing.ts
- apps/web/module/Admin/Listings/Live/Activity/Itinerary/index.tsx
- apps/web/module/Admin/Listings/hooks/useGetRentalById.ts
- apps/web/module/Admin/Listings/hooks/useUpdateRentalBasicInfo.ts
Update rental details v2 hook implementation
> [Story-Feature] Implement Update Rental Details

- apps/api/src/routes/api/rentals-v2/index.ts
- apps/web/module/Hosting/Listings/Rentals/Rental/hooks/useGetRentalPricing.ts
Added useGetRentalPricing hook v2. The hook is working and tested.
> [Story-Feature] Added useGetRentalPricing hook v2

- apps/web/module/Admin/Listings/Declined/Rental/AddOns/index.tsx
- apps/web/module/Admin/Listings/Declined/Rental/Details/index.tsx
- apps/web/module/Admin/Listings/Declined/Rental/Location/index.tsx
- apps/web/module/Admin/Listings/Declined/Rental/Photos/index.tsx
- apps/web/module/Admin/Listings/Declined/Rental/Pricing/index.tsx
- apps/web/module/Admin/Listings/Live/Activity/Itinerary/index.tsx
- apps/web/module/Hosting/Listings/Rentals/Rental/Details/index.tsx
- apps/web/module/Hosting/Listings/Rentals/Rental/Summary/index.tsx
- apps/web/module/Hosting/Listings/Rentals/Rental/hooks/useUpdateRentalDetails.ts
- apps/web/module/Hosting/Listings/Rentals/Rental/hooks/useUpdateRentalStatusById.ts
Implemented update rental status api v2 in frontend
> [Story-Feature] Implemented update rental status api v2 in frontend

- apps/web/module/Hosting/Listings/Rentals/Rental/Pricing/index.tsx
- apps/web/module/Hosting/Listings/Rentals/Rental/hooks/useUpdateRentalPricing.ts
Modified useUpdateRentalPricing hook to v2. Not tested yet. The useGetRentalBasicInfo is tested working.
> [Story-Feature] Modified useUpdateRentalPricing hook to v2

- apps/api/src/routes/api/rentals-v2/index.ts
- apps/web/module/Admin/Listings/Declined/Rental/Photos/PhotosModal.tsx
- apps/web/module/Admin/Listings/ForReview/Property/BasicInfo/index.tsx
- apps/web/module/Admin/Listings/ForReview/Property/Facilities/index.tsx
- apps/web/module/Admin/Listings/ForReview/Property/Location.tsx
- apps/web/module/Admin/Listings/ForReview/Property/Photos/PhotosModal.tsx
- apps/web/module/Admin/Listings/ForReview/Property/Photos/index.tsx
- apps/web/module/Admin/Listings/ForReview/Property/Policies/index.tsx
- apps/web/module/Admin/Listings/ForReview/Property/Pricing/index.tsx
- apps/web/module/Admin/Listings/ForReview/Property/PropertyType.tsx
- apps/web/module/Admin/Listings/ForReview/Property/Units/UnitsTable.tsx
- apps/web/module/Admin/Listings/ForReview/Property/Units/index.tsx
- apps/web/module/Admin/Listings/hooks/useGetPropertyById.ts
- apps/web/module/Admin/Listings/hooks/useUpdatePropertyBasicInfo.ts
- apps/web/module/Admin/Listings/hooks/useUpdatePropertyFacilities.ts
- apps/web/module/Admin/Listings/hooks/useUpdatePropertyLocation.ts
- apps/web/module/Admin/Listings/hooks/useUpdatePropertyPhotos.ts
- apps/web/module/Admin/Listings/hooks/useUpdatePropertyPolicies.ts
- apps/web/module/Admin/Listings/hooks/useUpdatePropertyType.ts
- apps/web/module/Hosting/Listings/Rentals/Rental/AddOns/index.tsx
- apps/web/module/Hosting/Listings/Rentals/Rental/hooks/useUpdateRentalAddOns.ts
Update rental addOns v2 hook implementation
> [Story-Feature] Implement Update Rental Addons

- apps/api/src/routes/api/rentals-v2/index.ts
- apps/web/module/Admin/Listings/Declined/Rental/hooks/useGetRentalPhotosById.ts
- apps/web/module/Hosting/Listings/Rentals/Rental/hooks/useGetRentalPhotosById.ts
Modified useGetPhotosById hook to v2. This is tested.
> [Story-Feature] Modified useGetRentalPhotosById hook to v2

- apps/api/src/routes/api/rentals-v2/services/finishedSections.ts
- apps/web/module/Hosting/Listings/Rentals/Rental/hooks/useUpdateRentalFinshedSection.ts
Implemented update finished section in frontend hook
> feat: Implemented update finished section in frontend hook

- apps/web/module/Hosting/Listings/Rentals/Rental/Photos/index.tsx
- apps/web/module/Hosting/Listings/Rentals/Rental/hooks/useUpdateRentalPhotos.ts
Update rental photos v2 hook implementation
> [Story-Feature] Implement Update Rental Photos

- apps/web/module/Admin/Listings/Declined/Rental/hooks/useDeleteRentalPhotos.ts
- apps/web/module/Hosting/Listings/Rentals/Rental/hooks/useDeleteRentalPhotos.ts
Delete rental photo by photoId v2 hook implementation
> [Story-Feature] Implement Delete rental photo by photoId api v2

- apps/web/module/Admin/Listings/Declined/Rental/hooks/useDeleteRentals.ts
- apps/web/module/Hosting/Listings/Rentals/Rental/hooks/useDeleteRentals.ts
Implemented delete rental api v2 to frontend hook
> [Story-Feature] Implemented delete rental api v2 to frontend hook

- packages/database/mongo/models/dbActivities.ts
- packages/database/mongo/models/dbActivityItineraries.ts
- packages/database/mongo/models/index.ts
Added database model activities and itineraries for api v2
> [Story-feature] Added database model activities and itineraries

- apps/api/src/routes/api/rentals-v2/index.ts
- apps/api/src/routes/api/rentals-v2/services/default.ts
- apps/web/module/Admin/Listings/Declined/Rental/hooks/useAddRentals.ts
- apps/web/module/Hosting/Listings/Rentals/Rental/hooks/useAddRentals.ts
> [Story-Feature] Bug Add Rental

- apps/api/src/routes/api/activities-v2/middleware/isHostActivityOwner.ts
Created isHostActivityOwner middleware v2. This needs testing.
> [Story-Feature] Created isHostActivityOwner middleware v2

- apps/web/dummy.tsx
- apps/web/module/Hosting/Insights/index.tsx
- apps/web/module/Hosting/PaymentHistory/Graph.tsx
- apps/web/module/Hosting/PaymentHistory/GraphTab.tsx
- apps/web/module/Hosting/PaymentHistory/components/OverAllSummary.tsx
- apps/web/module/Hosting/PaymentHistory/hooks/useGetFilteredPaymentHistory.tsx
> [ Story - Feature ] Add the year and month filter with all option for month

- apps/api/src/routes/api/activities-v2/index.ts
- apps/api/src/routes/api/activities-v2/middleware/isHostActivityOwner.ts
- apps/api/src/routes/api/activities-v2/services/default.ts
- apps/api/src/routes/index.ts
Added get one activity endpoint api v2
> [Story - Feature] Added get one activity endpoint api v2

- apps/web/module/Hosting/PaymentHistory/GraphTab.tsx
- apps/web/module/Hosting/PaymentHistory/components/OverAllSummary.tsx
> [ Story - Feature ]  Add the year and month filter with all option for month

- apps/api/src/routes/api/activities-v2/middleware/isHostActivityOwner.ts
- apps/api/src/routes/api/activities-v2/services/default.ts
Converted add blank activity to api v2. This needs testing. Also adjusted import of dbAcitivities from isHostAcitivtyOwner in this ticket.
> [Story-Feature] Converted add blank activity to api v2

- apps/api/src/routes/api/activities-v2/index.ts
- apps/api/src/routes/api/activities-v2/services/addionalInfo.ts
Converted get additional info api v2
> [Story-feature] Converted get additional info api v2

- apps/api/src/routes/api/activities-v2/index.ts
- apps/api/src/routes/api/activities-v2/middleware/isHostActivityOwner.ts
- apps/api/src/routes/api/activities-v2/services/basic-info.ts
Converted update activity basic info api v2
> [Story-Feature] Converted update activity basic info api v2

- apps/api/src/routes/api/activities-v2/index.ts
- apps/api/src/routes/api/activities-v2/services/activity-inclussions.ts
- apps/api/src/routes/api/activities-v2/services/default.ts
Converted get activity inclussion to api v2. This is tested.
> [Story-Feature] Converted get activity inclussions to api v2

- apps/api/src/routes/api/activities-v2/index.ts
- apps/api/src/routes/api/activities-v2/services/additionalInfo.ts
- apps/api/src/routes/mock/activities/service/additionalInfo.ts
Update additional info API v2 implementation
> [Story-Feature] Convert Update additional info to api v2

- apps/api/src/routes/api/activities-v2/index.ts
- apps/api/src/routes/api/activities-v2/services/additionalInfo.ts
- apps/api/src/routes/api/activities-v2/services/finishedSections.ts
- apps/web/module/Hosting/Listings/Activities/Activity/BasicInfo/index.tsx
- apps/web/module/Hosting/Listings/Activities/Activity/Inclusions/index.tsx
Update activity finished section to api v2
> [Story-Feature] Convert Update activity finished section to api v2

- apps/api/src/routes/api/activities-v2/index.ts
- apps/api/src/routes/api/users-v2/email-template/host/BecomeHostEmailConfirmation.tsx
Fixed Wrong title of email in apply as host
> [Story-Feature] Fixed Wrong title of email in apply as host

- apps/api/src/routes/api/activities-v2/index.ts
Remove duplicate endpoints in activity index.ts
> [Story-Feature] Remove duplicate endpoints in activity index.ts

- apps/web/module/Admin/Listings/hooks/useAddBlankActivity.ts
- apps/web/module/Hosting/Listings/hooks/useAddBlankActivity.ts
Implemented add blank activity api v2 to frontend
> [Story-Feature] Implemented add blank activity api v2 to frontend

- apps/web/module/Hosting/Listings/Activities/hooks/useGetActivityBasicInfo.ts
Added useGetActivityBasicInfo custom hook api v2
> [Story-Feature] Added useGetActivityBasicInfo custom hook api v2

- apps/web/module/Admin/Activity/hooks/useGetActivitiesById.ts
- apps/web/module/Hosting/Activity/hooks/useGetActivitiesById.ts
- apps/web/module/Hosting/Listings/Activities/Activity/BasicInfo/index.tsx
Get single activity api v2 hook implementation
> [Story-Feature] Implement get single activity api v2

- apps/api/src/routes/api/activities-v2/services/default.ts
- apps/web/module/Admin/Listings/components/modals/SelectListingTypeModal.tsx
- apps/web/module/Hosting/Listings/Activities/Activity/Inclusions/index.tsx
- apps/web/module/Hosting/Listings/Activities/hooks/useGetActivityInclusionsById.ts
- apps/web/module/Hosting/Listings/components/modals/SelectListingTypeModal.tsx
Implemented get inclusions api v2 to frontend
> [Story-Feature] Implemented get inclusions api v2 to frontend

- apps/web/module/Hosting/Listings/Rentals/Rental/Details/index.tsx
- packages/database/mongo/models/dbRentals.ts
Fixed error on adding rental details in engine capacity
> [Bug-Feature] Fixed error on adding rental details in engine capacity

- apps/web/module/Hosting/Listings/Activities/Activity/AdditionalInfo/index.tsx
- apps/web/module/Hosting/Listings/Activities/hooks/useGetAdditionalInfoByActivityId.ts
Implemented get activity additional info api v2. Not yet tested.
> [Story-Feature] Implement get activity additional info api v2

- apps/web/module/Admin/Activity/hooks/useUpdateAdditionalInfoActivities.ts
- apps/web/module/Hosting/Activity/hooks/useUpdateAdditionalInfoActivities.ts
- apps/web/module/Hosting/Listings/Activities/Activity/AdditionalInfo/index.tsx
- apps/web/module/Hosting/Listings/Activities/hooks/useUpdateActivityAdditionalInfo.ts
Implemented update activity additional info api v2 in frontend
> ]Story- Feature] Implemented update activity additional info api v2 in frontend

- apps/api/src/routes/api/activities-v2/index.ts
- apps/api/src/routes/api/activities-v2/services/default.ts
Get activities by host id API v2 implementation
> [Story-Feature] Created get activity by host endpoint api v2

- apps/web/module/Hosting/Listings/Activities/Activity/Inclusions/index.tsx
- apps/web/module/Hosting/Listings/Activities/hooks/useUpdateActivityInclusions.ts
Implemented update activity inclussions to api v2. This is not yet tested.
> [Story-Feature] Implement update activity inclussions api v2

- apps/web/module/Hosting/Activity/hooks/useUpdateActivityStatus.ts
Update activity status v2 hook implementation
> [Story-Feature] Implement update activity status api v2

- apps/api/src/routes/api/activities-v2/services/default.ts
- apps/web/module/Hosting/Activity/hooks/useGetActivitiesByHost.ts
- apps/web/module/Hosting/Listings/Activities/index.tsx
- apps/web/module/Hosting/Listings/Rentals/index.tsx
- packages/database/mongo/models/dbActivities.ts
Implemented get activities by host api v2
> [Story-Feature] Implemented get activities by host api v2

- apps/web/common/components/AdminLayout/NewListingActivitySidebar.tsx
- apps/web/common/components/AdminLayout/NewListingRentalSidebar.tsx
- apps/web/common/components/AdminLayout/NewListingSidebar.tsx
- apps/web/common/components/HostLayout/NewListingActivitySidebar.tsx
- apps/web/common/components/HostLayout/NewListingRentalSidebar.tsx
- apps/web/common/components/HostLayout/NewListingSidebar.tsx
- apps/web/module/Admin/Listings/hooks/useUpdateActivityFinishedSections.ts
- apps/web/module/Admin/Listings/hooks/useUpdateFinishedSections.ts
- apps/web/module/Hosting/Activity/hooks/useUpdateActivityStatus.ts
- apps/web/module/Hosting/Listings/Activities/Activity/Inclusions/index.tsx
- apps/web/module/Hosting/Listings/Activities/hooks/useUpdateActivityFinishedSections.ts
- apps/web/module/Hosting/Listings/Activities/hooks/useUpdateActivityInclusions.ts
- apps/web/module/Hosting/Listings/hooks/useGetFinishedSections.ts
- apps/web/module/Hosting/Listings/hooks/useUpdateActivityFinishedSections.ts
Implement update activity finished sections api v2. Need further testing.
> [Story-Feature] Implemented update activity finished sections api v2

- apps/web/common/components/HostLayout/ListingActivitySidebar.tsx
- apps/web/common/components/HostLayout/ListingRentalSidebar.tsx
- apps/web/module/Hosting/Listings/Activities/Activity/BasicInfo/index.tsx
- apps/web/module/Hosting/Listings/Activities/Activity/Inclusions/index.tsx
Fixed error on adding and edditing activity inclusions
> [Bug-Feature] Fixed error on adding and edditing activity inclusions

- apps/api/src/routes/api/properties-v2/index.ts
- apps/api/src/routes/api/properties-v2/middlewares/isHostPropertyOwner.ts
- apps/api/src/routes/api/properties-v2/services/photos.ts
- apps/api/src/routes/api/rentals-v2/services/photos.ts
- apps/api/src/routes/index.ts
- apps/web/module/LandingPage/index.tsx
- packages/contract/src/Photo/type.ts
- packages/contract/src/Photo/zod.ts
- packages/database/mongo/models/dbPhotos.ts
> feat(api): Added property photos endpoints

- apps/web/module/Hosting/Listings/Rentals/Rental/Details/index.tsx
Fixed error on getting data on activity details
> [Bug-Feature] Fixed error on getting data on activity details

- apps/api/src/routes/api/rentals-v2/services/addOns.ts
Fixed error on rental sidebar no turning green after updating Addons
> [Bug-Feature] Fixed error on rental sidebar no turning green after updating Addons

- apps/api/src/routes/api/rentals-v2/services/rates.ts
- apps/web/module/Hosting/Listings/Rentals/Rental/Pricing/index.tsx
Fixed bug on not displaying current rental price
> fix: Fixed bug on not displaying current rental price

- apps/api/src/routes/api/rentals-v2/services/addOns.ts
- apps/web/module/Hosting/Listings/Rentals/Rental/AddOns/index.tsx
Fixed addons not showing data in addons after saving
> [Story-Feature] Addons not showing data in addons after saving

- apps/api/src/routes/api/activities-v2/services/basic-info.ts
- apps/api/src/routes/mock/activities/service/basic-info.ts
- apps/web/module/Hosting/Listings/Activities/Activity/BasicInfo/index.tsx
- packages/contract/src/Activities/zod.ts
Fixed activity basic info not saving the language.Tested.
> [Story-Feature] Activity basic info not saving the language

- apps/web/module/Admin/Listings/Declined/Rental/Location/index.tsx
- apps/web/module/Admin/Listings/ForReview/Property/Location.tsx
- apps/web/module/Admin/Listings/Live/Activity/Itinerary/index.tsx
- apps/web/module/Hosting/Listings/Activities/Activity/Itinerary/index.tsx
- apps/web/module/Hosting/Listings/Properties/Property/Location.tsx
- apps/web/module/Hosting/Listings/Rentals/Rental/Location/index.tsx
- apps/web/module/Hosting/Listings/Rentals/Rental/Summary/Details/Car.tsx
- apps/web/module/Hosting/Listings/Rentals/Rental/Summary/index.tsx
- apps/web/module/Hosting/Listings/Rentals/Rental/hooks/useGetRentalLocation.ts
- packages/constants/src/barangay-municipalities.ts
- packages/contract/src/ListingLocation/zod.ts
fixed location not showing data after savings in rental location
> [Bug-Feature] Location not showing data after savings in rental location

- apps/api/src/routes/api/properties-v2/middlewares/isHostPropertyOwner.ts
isHostPropertyOwner middleware for api v2 implementation
> [Story-Feature] isHostPropertyOwner middleware for api v2

- packages/database/mongo/models/dbAmenities.ts
- packages/database/mongo/models/dbBedConfigs.ts
- packages/database/mongo/models/dbBookableUnitTypes.ts
- packages/database/mongo/models/dbBookableUnits.ts
- packages/database/mongo/models/dbFacilities.ts
- packages/database/mongo/models/dbPolicies.ts
- packages/database/mongo/models/dbProperties.ts
- packages/database/mongo/models/dbReservations.ts
- packages/database/mongo/models/dbUnitPrices.ts
- packages/database/mongo/models/index.ts
Property model and related schema for api v2
> [Story-Feature] Created property model and related schema for api v2

- apps/api/src/routes/api/properties-v2/index.ts
- apps/api/src/routes/api/properties-v2/services/default.ts
Converted get properties by hst endpoint to api v2
> [Story-Feature] Converted get properties by host endpoint to api v2

- apps/web/module/Hosting/Listings/Activities/Activity/Itinerary/index.tsx
- apps/web/module/Hosting/Listings/Activities/Activity/Summary/index.tsx
- apps/web/module/Hosting/Listings/Activities/hooks/useUpdateActivityItinerary.ts
- apps/web/module/Hosting/Listings/Rentals/Rental/Details/index.tsx
Fixed bug for rental details isRegistered vehicle radio button
> [Bug-Feature] Fixed bug for rental details isRegistered vehicle radio button

- apps/api/src/routes/api/properties-v2/index.ts
- apps/api/src/routes/api/properties-v2/middlewares/isHostPropertyOwner.ts
- apps/api/src/routes/api/properties-v2/services/default.ts
- packages/database/mongo/models/dbProperties.ts
Converted get property by id endpoint to api v2
> [Story-Feature] Converted get property by id endpoint to api v2

- apps/web/app/(blog-guide)/guide/travel/[travelName]/page.tsx
- apps/web/app/(blog-guide)/layout.tsx
- apps/web/common/components/HeaderGuides.tsx
- apps/web/module/Accommodation/components/ImageGallery.tsx
- apps/web/module/Accommodation/components/SectionInfo.tsx
- apps/web/module/Accommodation/types/SectionInfo.d.ts
- apps/web/module/BlogGuide/Guide/SurfingGuide/SurfGuide.tsx
- apps/web/module/BlogGuide/Guide/SurfingGuide/index.tsx
- apps/web/module/BlogGuide/Guide/TravelBlog/PopularGuides.tsx
- apps/web/module/BlogGuide/Guide/TravelBlog/TopThingsToDo.tsx
- apps/web/module/BlogGuide/Guide/TravelBlog/TravelChecklist.tsx
- apps/web/module/BlogGuide/Guide/TravelBlog/TravelImages.tsx
- apps/web/module/BlogGuide/Guide/TravelBlog/components/GridImage.tsx
- apps/web/module/BlogGuide/Guide/TravelBlog/index.tsx
- apps/web/module/BlogGuide/data.json
> 297 feature general blog UI

- apps/api/src/routes/api/properties-v2/index.ts
- apps/api/src/routes/api/properties-v2/services/default.ts
Converted delete property endpoint to api v2
> [Story-Feature] Converted delete property endpoint to api v2

- apps/api/src/routes/api/properties-v2/index.ts
- apps/api/src/routes/api/properties-v2/services/default.ts
Converted get property type endpoint to api v2
> [Story-Feature] Converted get property type endpoint to api v2

- apps/api/src/routes/api/activities-v2/index.ts
- apps/api/src/routes/api/activities-v2/services/default.ts
- apps/api/src/routes/api/activities-v2/services/photos.ts
- apps/web/module/Hosting/Listings/Activities/Activity/Itinerary/index.tsx
- apps/web/module/Hosting/Listings/Activities/Activity/Summary/index.tsx
Added activity photos endpoint and implement it to frontend
> [Story-Feature] Added activity photos endpoint and implement it to frontend

- apps/api/src/routes/api/properties-v2/index.ts
- apps/api/src/routes/api/properties-v2/services/default.ts
Converted update property type endpoint to api v2
> [Story-Feature] Converted update property type endpoint to api v2

- apps/api/src/routes/api/activities-v2/index.ts
- apps/api/src/routes/api/activities-v2/services/default.ts
- packages/database/mongo/models/dbActivities.ts
Add Itinerary endpoint to api v2 implementation
> [Story-Feature] Convert Mock update Itinerary endpoint to api v2

- apps/api/src/routes/api/activities-v2/services/default.ts
- apps/web/common/components/HostLayout/ListingActivityHeader.tsx
- apps/web/module/Hosting/Listings/Activities/Activity/Itinerary/index.tsx
- apps/web/module/Hosting/Listings/Activities/Activity/Itinerary/modals/BuilderModal.tsx
- apps/web/module/Hosting/Listings/Activities/hooks/useUpdateActivityItinerary.ts
- packages/database/mongo/models/dbActivities.ts
Implemented get itinerary to frontend
> [Story-Feature] Implemented get itinerary to frontend

- apps/api/src/routes/api/activities-v2/services/default.ts
- apps/web/module/Hosting/Listings/Activities/Activity/Itinerary/index.tsx
- apps/web/module/Hosting/Listings/Activities/hooks/useUpdateActivityItinerary.ts
Implement update itinerary to frontend
> [Story-Feature] Implement update itinerary to frontend

- apps/web/module/Hosting/Listings/Activities/Activity/Itinerary/index.tsx
Fixed activity Itinerary code base
> [Bug-Feature] Fixed activity Itinerary code base

- apps/api/src/routes/api/properties-v2/index.ts
- apps/api/src/routes/api/properties-v2/services/default.ts
Converted get property basic info endpoint to api v2
> [Story-Feature] Converted get property basic info endpoint to api v2

- apps/api/src/routes/api/properties-v2/index.ts
- apps/api/src/routes/api/properties-v2/services/propertyType.ts
- packages/database/mongo/models/dbProperties.ts
Added add property type to api v2
> [Story-Feature] Added add property type to api v2

- apps/api/src/routes/api/properties-v2/index.ts
- apps/api/src/routes/api/properties-v2/services/facilities.ts
Added get property facilities endpoint to api v2
> [Story-Feature] Added get property facilities endpoint to api v2

- apps/api/src/routes/api/properties-v2/index.ts
- apps/api/src/routes/api/properties-v2/services/status.ts
- packages/database/mongo/models/index.ts
Converted property update status endpoint to api v2
> [Story - Feature] Converted property update status endpoint to api v2

- apps/api/src/routes/api/properties-v2/index.ts
- apps/api/src/routes/api/properties-v2/services/finishedSections.ts
Converted property  update finished sections to api v2
> [Story - Feature] Converted property  update finished sections to api v2

- apps/api/src/routes/api/properties-v2/index.ts
- apps/api/src/routes/api/properties-v2/services/policies.ts
Converted get property policies to api v2
> [Story - Feature] Converted get property policies to api v2

- apps/api/src/routes/api/properties-v2/index.ts
- apps/api/src/routes/api/properties-v2/services/units.ts
Converted create room unit endpoint to api v2
> [Story - Feature] Converted create room unit endpoint to api v2

- apps/api/src/routes/api/properties-v2/index.ts
- apps/api/src/routes/api/properties-v2/services/units.ts
- packages/contract/src/BookableUnitType/zod.ts
Converted get bookable units by category to api v2
> feat(api): Converted get bookable units by category to api v2

- apps/api/src/routes/api/properties-v2/index.ts
- apps/api/src/routes/api/properties-v2/services/amenities.ts
- packages/database/mongo/models/dbAmenities.ts
- packages/database/mongo/models/dbBookableUnitTypes.ts
Converted property update amenities to api v2
> [Story- Feature] Converted property update amenities to api v2

- apps/web/module/Hosting/Listings/Properties/hooks/useAddBlankProperty.ts
- apps/web/module/Hosting/Listings/components/modals/SelectListingTypeModal.tsx
Add blank property frontend v2 hook implementation
> [Story-Feature] Implemented add blank property to frontend

- apps/web/module/Hosting/Listings/Properties/hooks/useGetPropertyByHost.ts
Implemented get property by host to frontend. This is not tested yet.
> [Story-Feature] Implemented get property by host to frontend

- apps/web/module/Hosting/Listings/Properties/hooks/useDeleteProperty.ts
Delete property to frontend v2 hook implementation
> [Story-Feature] Implement delete property to frontend

- apps/api/src/routes/api/properties-v2/index.ts
- apps/api/src/routes/api/properties-v2/services/amenities.ts
Converted property bookable unit get amenities to api v2
> [Story-Feature] Converted property bookable unit get amenities to api v2

- apps/api/src/routes/api/properties-v2/services/default.ts
- apps/web/module/Hosting/Listings/Properties/Property/PropertyType.tsx
- apps/web/module/Hosting/Listings/Properties/hooks/useUpdatePropertyFinishedSections.ts
- apps/web/module/Hosting/Listings/Properties/hooks/useUpdatePropertyType.ts
Update property type api v2 to frontend implementation
> [Story-Feature] Implemented update property type api v2 to frontend

- apps/api/src/routes/api/properties-v2/index.ts
- apps/api/src/routes/api/properties-v2/services/unitPrice.ts
- apps/api/src/routes/mock/properties/service/unitPrice.ts
- packages/contract/src/BookableUnitType/zod.ts
- packages/contract/src/UnitPrice/zod.ts
- packages/database/mongo/models/dbBookableUnitTypes.ts
Converted update property bookable unit price to api v2
> [Story-Feature] Converted update property bookable unit price to api v2

- apps/api/src/routes/api/properties-v2/services/default.ts
- apps/web/module/Hosting/Listings/Properties/Property/BasicInfo/index.tsx
- apps/web/module/Hosting/Listings/Properties/hooks/useUpdatePropertyBasicInfo.ts
Update property basic info api v2 to frontend implementation
> [Story-Feature] Implement update property basic info api v2 to frontend

- apps/api/src/routes/api/properties-v2/services/default.ts
- apps/web/module/Hosting/Listings/Properties/Property/Location.tsx
- apps/web/module/Hosting/Listings/Properties/hooks/useUpdatePropertyLocation.ts
Update property location api v2 to frontend implementation
> [Story-Feature] Implement update property location api v2 to frontend

- apps/web/module/Hosting/Listings/Properties/Property/Policies/index.tsx
- apps/web/module/Hosting/Listings/Properties/hooks/useUpdatePropertyPolicies.ts
Update property policies api v2 to frontend implementation
> [Story-Feature] Implement update property policies api v2 to frontend

- apps/web/module/Hosting/Listings/Properties/hooks/useUpdatePropertyStatusById.ts
Update property status api v2 to frontend implementation
> [Story-Feature] Implement update property status api v2 to frontend

- apps/api/src/routes/api/properties-v2/index.ts
- apps/api/src/routes/api/properties-v2/services/amenities.ts
- apps/api/src/routes/api/properties-v2/services/facilities.ts
- packages/contract/src/Property/zod.ts
- packages/database/mongo/models/dbFacilities.ts
Converted property update facilities to api v2
> [Story-Feature] Converted property update facilities to api v2

- apps/api/src/routes/api/properties-v2/index.ts
- apps/api/src/routes/api/properties-v2/services/photos.ts
- apps/web/module/Hosting/Listings/Properties/Property/Location.tsx
Converted property photos to api v2
> [Story-Feature] Converted property photos to api v2

- apps/web/module/Hosting/Listings/Properties/Property/Facilities/index.tsx
- apps/web/module/Hosting/Listings/Properties/Property/Location.tsx
- apps/web/module/Hosting/Listings/Properties/hooks/useUpdatePropertyFacilities.ts
Implemented update facilities endpoint api v2 to frontend
> [Story-Feature] Implemented update facilities endpoint api v2 to frontend

- apps/api/src/routes/api/properties-v2/services/finishedSections.ts
- apps/web/module/Hosting/Listings/Properties/Property/Photos/index.tsx
- apps/web/module/Hosting/Listings/Properties/hooks/useAddPropertyPhotos.ts
- apps/web/module/Hosting/Listings/Properties/hooks/useDeletePropertyPhoto.ts
- apps/web/module/Hosting/Listings/Properties/hooks/useGetPropertyPhotosById.ts
- apps/web/module/Hosting/Listings/Properties/hooks/useUpdatePropertyFinishedSections.ts
- apps/web/module/Hosting/Listings/Properties/hooks/useUpdatePropertyPhoto.ts
Implemented photos in property frontend
> [Story-Feature] Implemented photos in property frontend

- apps/web/module/Hosting/Listings/Properties/Property/Location.tsx
Fixed error on property setup locations
> [Bug-Feature] Fixed error on property setup locations

- apps/api/src/routes/api/properties-v2/services/default.ts
- apps/web/module/Hosting/Listings/Properties/index.tsx
Corrected display information in properties list page
> [Story-Feature] Corrected display information in properties list page

- apps/api/src/routes/api/properties-v2/services/default.ts
- apps/web/module/Admin/Listings/ForReview/Property/Units/modals/SelectUnitTypeModal.tsx
- apps/web/module/Hosting/Listings/Activities/Activity/Summary/index.tsx
- apps/web/module/Hosting/Listings/Properties/Property/Facilities/index.tsx
- apps/web/module/Hosting/Listings/Properties/Property/Location.tsx
- apps/web/module/Hosting/Listings/Properties/Property/Policies/index.tsx
- apps/web/module/Hosting/Listings/Properties/Property/Summary/index.tsx
- apps/web/module/Hosting/Listings/Properties/Property/Units/modals/SelectUnitTypeModal.tsx
- packages/contract/src/Property/enum.ts
- packages/contract/src/Property/index.ts
- packages/contract/src/Property/zod.ts
Property summary implementation available data only
> [Story-Feature] Implement api v2 to property summary available data only

- apps/api/src/routes/api/properties-v2/services/policies.ts
Policies additional rules included in the process
> [Bug-Feature] Backend policies additional rules not included in process

- apps/web/module/Hosting/Listings/Properties/Property/Location.tsx
- apps/web/module/Hosting/Listings/Properties/Property/Pricing/index.tsx
- apps/web/module/Hosting/Listings/Properties/Property/Summary/index.tsx
- apps/web/module/Hosting/Listings/Properties/Property/Units/index.tsx
Fixed not all in property setup sidebar not turning to green
> [Bug-Feature] Fixed not all in property setup sidebar not turning to green

- apps/web/module/Hosting/Listings/Properties/Property/Summary/index.tsx
Included Photos and facilities to current summary
> [Story-Feature] Include Photos and facilities to current summary

- apps/api/src/routes/api/properties-v2/index.ts
- apps/api/src/routes/api/properties-v2/services/units.ts
Created update basic info for bed unit api v2
> [Story-Feature] Created update basic info for bed unit api v2

- apps/api/src/routes/api/properties-v2/index.ts
- apps/api/src/routes/api/properties-v2/services/units.ts
Created update room unit basic info api v2
> feat(api): Created update room unit basic info api v2

- apps/web/module/Hosting/Listings/Properties/Property/Units/components/UnitsTable.tsx
Implemented bookable units lists
> [Story-Feature] Implemented bookable units lists

- apps/api/src/routes/api/properties-v2/index.ts
- apps/api/src/routes/api/properties-v2/services/units.ts
Created update whole place unit basic info api v2
> [Story - Feature] Created update whole place unit basic info api v2

- apps/api/src/routes/api/properties-v2/services/default.ts
- apps/api/src/routes/api/properties-v2/services/units.ts
- apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/Room.tsx
- apps/web/module/Hosting/Listings/Properties/Property/Units/components/UnitsTable.tsx
- apps/web/module/Hosting/Listings/Properties/hooks/useUpdateRoomBasicInfo.ts
- packages/database/mongo/models/dbBookableUnitTypes.ts
Created update unit room frontend
> [Story-Feature] Created update unit room frontend

- apps/api/src/routes/api/properties-v2/services/amenities.ts
- apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/WholePlace.tsx
- packages/contract/src/Property/zod.ts
Fixed Error on amenities frontend and backend
> [Bug-Feature] Fixed Error on amenities frontend and backend

- apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/Bed.tsx
- apps/web/module/Hosting/Listings/Properties/hooks/useUpdateBedBasicInfo.ts
> [Story-Feature] Added Bed bookable unit

- apps/web/module/Listing/Activity/Itinerary/Builder.tsx
- apps/web/module/Listing/Activity/index.tsx
> [ Story - Feature ] Add the itinerary builder

- apps/web/app/(listing-acco)/hosting/listings/properties/[listingId]/units/bed/[bedId]/edit/page.tsx
- apps/web/app/(listing-acco)/hosting/listings/properties/[listingId]/units/room/[roomId]/edit/page.tsx
- apps/web/app/(new-listing-acco)/hosting/listings/properties/setup/[listingId]/units/beds/[bedId]/edit/page.tsx
- apps/web/app/(new-listing-acco)/hosting/listings/properties/setup/[listingId]/units/rooms/[roomId]/edit/page.tsx
- apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/Bed.tsx
- apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/Room.tsx
- apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/WholePlace.tsx
Fixed already filled amenities
> [Story-Feature] Fixed already filled amenities

- apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/Bed.tsx
- apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/Room.tsx
Fixed error on unit back button
> [Bug-Feature] Fixed error on unit back button

- apps/web/module/Hosting/Listings/Properties/Property/Summary/index.tsx
> [Story-Feature] Added units in summary

- apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/WholePlace.tsx
Fixed input number in whole place error if click add
> [Bug-Feature] Fixed input number in whole place error if click add

- apps/web/common/components/HostLayout/ListingHeader.tsx
Fixed breadcrumbs in edit page will be title of property
> [Bug-Feature] Fixed breadcrumbs in edit page will be title of property

- apps/web/module/Hosting/Listings/Properties/Property/PropertyType.tsx
Removed save change button in edit property type
> [Bug-Feature] Removed save change button in edit property type

- packages/database/mongo/models/dbReservations.ts
- pnpm-lock.yaml
Created reservation model schema
> [Story-Feature] Created reservation model schema

- apps/web/module/Hosting/Listings/Activities/Activity/AdditionalInfo/index.tsx
- apps/web/module/Hosting/Listings/Activities/Activity/BasicInfo/index.tsx
- apps/web/module/Hosting/Listings/Activities/Activity/Inclusions/index.tsx
- apps/web/module/Hosting/Listings/Activities/Activity/Itinerary/index.tsx
- apps/web/module/Hosting/Listings/Properties/Property/BasicInfo/index.tsx
> feat: add descriptions under create listings inputs

- apps/api/src/routes/api/properties-v2/services/unitPrice.ts
- apps/api/src/routes/mock/properties/service/unitPrice.ts
- apps/web/common/components/HostLayout/ListingSidebar.tsx
- apps/web/common/components/HostLayout/NewListingSidebar.tsx
- apps/web/module/Hosting/Listings/Properties/Property/Photos/index.tsx
- apps/web/module/Hosting/Listings/Properties/Property/Pricing/PricingContent.tsx
- apps/web/module/Hosting/Listings/Properties/Property/Pricing/index.tsx
- apps/web/module/Hosting/Listings/Properties/Property/Units/index.tsx
- apps/web/module/Hosting/Listings/Properties/hooks/useGetPropertyUnitPricesById.ts
- apps/web/module/Hosting/Listings/Properties/hooks/useUpdatePropertyUnitPriceById.ts
- packages/contract/src/UnitPrice/zod.ts
> [ Feature - Develop ] Property units pricing

- apps/api/src/routes/api/rentals-v2/services/details.ts
- apps/api/src/routes/mock/rentals/service/details.ts
- apps/api/src/routes/mock/rentals/service/jsons/rentals.ts
- apps/web/module/Admin/Listings/Declined/Rental/Details/index.tsx
- apps/web/module/Hosting/Listings/Rentals/Rental/Details/index.tsx
- packages/contract/src/Rental/zod.ts
- packages/database/mongo/models/dbRentalDetails.ts
Removed Rental details minimum age and put driver license required
> [Story-Feature] Removed Rental details minimum age and put driver license required

- apps/api/src/routes/api/rentals-v2/services/addOns.ts
- apps/api/src/routes/mock/rentals/service/addOns.ts
- apps/api/src/routes/mock/rentals/service/jsons/rentals.ts
- apps/web/module/Hosting/Listings/Rentals/Rental/AddOns/index.tsx
- apps/web/module/Hosting/Listings/Rentals/Rental/Summary/Details/Bicycle.tsx
- apps/web/module/Hosting/Listings/Rentals/Rental/Summary/Details/Car.tsx
- apps/web/module/Hosting/Listings/Rentals/Rental/Summary/Details/Motorbike.tsx
- apps/web/module/Hosting/Listings/Rentals/Rental/Summary/index.tsx
- packages/contract/src/Rental/zod.ts
- packages/database/mongo/models/dbRentalAddOns.ts
Rental Addons in others enter new fields
> [Story-Feature] Rental Addons in others enter new fields

- packages/database/mongo/models/dbActivities.ts
> [Story-Feature] Modified activities schema

- apps/api/src/routes/api/activities-v2/services/default.ts
Include adding of slots and price in add blank activity endpoint
> [Story-Feature] Include adding of slots and price in add blank activity endpoint

- apps/api/src/routes/api/activities-v2/index.ts
- apps/api/src/routes/api/activities-v2/services/price-slots.ts
- packages/contract/src/Activities/type.ts
- packages/contract/src/Activities/zod.ts
- packages/database/mongo/models/dbActivities.ts
Created updated activity price and slots endpoint
> [Story-Feature] Created updated activity price and slots endpoint

- apps/web/module/BlogGuide/Guide/TravelBlog/PopularGuides.tsx
- apps/web/module/BlogGuide/Guide/TravelBlog/TopThingsToDo.tsx
- apps/web/module/BlogGuide/Guide/TravelBlog/TravelChecklist.tsx
- apps/web/module/BlogGuide/Guide/TravelBlog/TravelImages.tsx
- apps/web/module/BlogGuide/Guide/TravelBlog/index.tsx
- apps/web/module/BlogGuide/data.json
> [ Feature - Develop ] Guide location guide ui

- apps/web/app/(blog-guide)/layout.tsx
- apps/web/module/BlogGuide/Guide/RestaurantGuide/CheckoutBox.tsx
- apps/web/module/BlogGuide/Guide/RestaurantGuide/SectionInfo.tsx
- apps/web/module/BlogGuide/Guide/RestaurantGuide/components/ChefsNote.tsx
- apps/web/module/BlogGuide/Guide/RestaurantGuide/components/Contacts.tsx
- apps/web/module/BlogGuide/Guide/RestaurantGuide/components/OffersCuisine.tsx
- apps/web/module/BlogGuide/Guide/RestaurantGuide/components/OpeningHours.tsx
- apps/web/module/BlogGuide/Guide/RestaurantGuide/components/PriceLevel.tsx
- apps/web/module/BlogGuide/Guide/RestaurantGuide/components/ShareSave/index.tsx
- apps/web/module/BlogGuide/Guide/RestaurantGuide/components/ShareSave/modals/index.tsx
- apps/web/module/BlogGuide/Guide/RestaurantGuide/index.tsx
- apps/web/module/BlogGuide/Guide/RestaurantGuide/types/Contacts.d.ts
- apps/web/module/BlogGuide/Guide/RestaurantGuide/types/OffersCuisine.d.ts
- apps/web/module/BlogGuide/Guide/RestaurantGuide/types/PriceLevel.d.ts
- apps/web/module/BlogGuide/Guide/RestaurantGuide/types/Schedule.d.ts
- apps/web/module/BlogGuide/Header/index.tsx
> [Feature - Develop] Guide restaurant UI

- apps/web/module/Hosting/Listings/Rentals/Rental/Photos/index.tsx
- apps/web/module/Hosting/Listings/components/modals/EditPhotoModal.tsx
Added Example Rental photos description and tags
> [Story - Feature] Added Example Rental photos description and tags

- apps/api/src/routes/api/activities-v2/index.ts
- apps/api/src/routes/api/activities-v2/services/default.ts
- apps/api/src/routes/api/activities-v2/services/price-slots.ts
Include slots and price in get activity by id endpoint
> [Story-Feature] Include slots and price in get activity by id endpoint

- apps/api/src/routes/api/activities-v2/index.ts
- apps/api/src/routes/api/activities-v2/services/price-slots.ts
- apps/web/module/Hosting/Listings/Activities/hooks/useUpdateActivityPricingSlots.ts
Create custom hook for update activity pricing and slots
> [Story-Feature] Create custom hook for update activity pricing and slots

- packages/database/mongo/models/dbBookableUnitTypes.ts
Modify bookableUnitType Schema
> [Story-Feature] Modify bookableUnitType Schema

- apps/api/src/routes/api/activities-v2/services/default.ts
- packages/contract/src/Activities/zod.ts
- packages/database/mongo/models/dbActivities.ts
Fixed error on wrong field name on activity price
> [Bug-Feature] Fixed error on wrong field name on activity price

- apps/api/src/routes/api/activities-v2/index.ts
- apps/api/src/routes/api/activities-v2/services/default.ts
- apps/api/src/routes/api/activities-v2/services/price-slots.ts
- apps/web/module/Hosting/Listings/Activities/hooks/useUpdateActivityPricingSlots.ts
- packages/contract/src/Activities/type.ts
- packages/contract/src/Activities/zod.ts
- packages/database/mongo/models/dbActivities.ts
Created Activity pricing and slots backend
> [Feature-Feature] Activity pricing and slots backend

- apps/api/src/routes/api/properties-v2/services/units.ts
Modify add and update whole place endpoint
> [Story-Feature] Modify add and update whole place endpoint

- apps/api/src/routes/api/rentals-v2/services/addOns.ts
- apps/api/src/routes/mock/rentals/service/addOns.ts
- apps/api/src/routes/mock/rentals/service/jsons/rentals.ts
- apps/web/common/components/SpecificMap.tsx
- apps/web/module/Hosting/Listings/Rentals/Rental/AddOns/index.tsx
- apps/web/module/Hosting/Listings/Rentals/Rental/Location/index.tsx
- apps/web/module/Hosting/Listings/Rentals/Rental/Summary/Details/Bicycle.tsx
- apps/web/module/Hosting/Listings/Rentals/Rental/Summary/Details/Car.tsx
- apps/web/module/Hosting/Listings/Rentals/Rental/Summary/Details/Motorbike.tsx
- apps/web/module/Hosting/Listings/Rentals/Rental/Summary/index.tsx
- apps/web/module/Hosting/Listings/Rentals/Rental/modal/ConfirmationMapLocationModal.tsx
- apps/web/package.json
- packages/contract/src/Rental/zod.ts
- packages/database/mongo/models/dbRentalAddOns.ts
- pnpm-lock.yaml
Corrected typos, adjust the map modified to make it editable and scrollable only when clicked. Add filtering in characters in how to get there inputs and some minor adjustments in other field.
> [Story-Feature] rental location correct typo in description and put explain in detail how to get there

- apps/api/src/routes/api/properties-v2/index.ts
- apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/WholePlace.tsx
- apps/web/module/Hosting/Listings/Properties/hooks/useUpdateWholePlaceBasicInfo.ts
Connected Whole place bedrooms to backend
> [Story - Feature] Connected Whole place bedrooms to backend

- apps/web/common/components/ui/CreatableSelect.tsx
- apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/Bed.tsx
- apps/web/package.json
- pnpm-lock.yaml
Created select with custom input
> [Story-Feature] On bed and room name make it select with custom input

- apps/api/src/routes/api/properties-v2/services/units.ts
- apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/Room.tsx
- apps/web/module/Hosting/Listings/Properties/hooks/useUpdateRoomBasicInfo.ts
Implemented custom input in room unit
> [Story-Feature] Implemented custom input in room unit

- apps/api/src/routes/api/activities-v2/services/default.ts
- apps/web/module/Listing/Activity/CancellationPolicyModal.tsx
- apps/web/module/Listing/Activity/Itinerary/Builder.tsx
- apps/web/module/Listing/Activity/ThingsToKnow.tsx
- apps/web/module/Listing/Activity/ThingsToKnow/TitleLists.tsx
- apps/web/module/Listing/Activity/index.tsx
- apps/web/module/Listing/types/ThingsToKnow.d.ts
Connect public listing activity single view to backend
> [Feature-Feature] Connect public listing activity single view to backend

- apps/web/module/Hosting/Listings/Activities/Activity/Itinerary/index.tsx
- apps/web/module/Hosting/Listings/Properties/Property/Location.tsx
- apps/web/module/Hosting/Listings/Rentals/Rental/Location/index.tsx
> [Story-Feature] Put all the maps in modal

- apps/web/module/Hosting/Listings/Activities/Activity/AdditionalInfo/index.tsx
- apps/web/module/Hosting/Listings/Activities/Activity/BasicInfo/index.tsx
- apps/web/module/Hosting/Listings/Activities/Activity/Inclusions/index.tsx
- apps/web/module/Hosting/Listings/Activities/Activity/Itinerary/Builder.tsx
- apps/web/module/Hosting/Listings/Properties/Property/BasicInfo/index.tsx
- apps/web/module/Hosting/Listings/Properties/Property/Pricing/PricingContent.tsx
- apps/web/module/Hosting/Listings/Properties/Property/Summary/index.tsx
- apps/web/module/Hosting/Listings/Rentals/Rental/Summary/index.tsx
Add Margin 8 for all inputs in setup all categories
> [Story-Feature] Add Margin 8 for all inputs in setup all categories

- apps/web/module/Hosting/Listings/Activities/Activity/Photos/index.tsx
- apps/web/module/Hosting/Listings/Properties/Property/Photos/index.tsx
- apps/web/module/Hosting/Listings/Rentals/Rental/Photos/index.tsx
Photos description and tags now required in all categories
> [Story - Feature] Photos description and tags now required in all categories

- apps/web/app/(host)/hosting/payment-history/graph/page.tsx
- apps/web/common/components/HostLayout/Sidebar.tsx
- apps/web/module/Hosting/Earnings/EarningGraphTab.tsx
- apps/web/module/Hosting/Earnings/components/YearToDateSummaryBox.tsx
- apps/web/module/Hosting/Earnings/components/exportReportExcel.tsx
- apps/web/module/Hosting/Insights/helpers/insightsTabs.tsx
- apps/web/module/Hosting/Insights/index.tsx
- apps/web/module/Hosting/PaymentHistory/GraphTab.tsx
- apps/web/module/Hosting/PaymentHistory/components/OverAllSummary.tsx
- apps/web/module/Hosting/PaymentHistory/components/exportReportExcel.tsx
- apps/web/module/Hosting/PaymentHistory/hooks/useGetFilteredPaymentHistory.tsx
> [ Story - Feature ] Make insights payment history and earnings in insights sections

- apps/web/module/Hosting/Earnings/EarningsPaid.tsx
- apps/web/module/Hosting/Earnings/EarningsThisMonth.tsx
- apps/web/module/Hosting/Earnings/EarningsUpcoming.tsx
- apps/web/module/Hosting/Insights/index.tsx
- apps/web/module/Hosting/PaymentHistory/GraphTab.tsx
> [ Story - Feature ] Add descriptions on insights

- apps/web/module/Hosting/Listings/Properties/Property/Pricing/PricingContent.tsx
- apps/web/module/Hosting/Listings/Properties/Property/Pricing/index.tsx
- apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/Bed.tsx
- apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/Room.tsx
- apps/web/module/Hosting/Listings/Properties/Property/Units/components/UnitsTable.tsx
Make it again a dropdown then the last choice is custom
> [Bug-Feature] Make it again a dropdown then the last choice is custom

- apps/web/common/components/CustomSpecificMap.tsx
Apply the map logic onclick of category location setup to activity itinerary
> [Story-Feature] Apply the map logic onclick of category location setup to activity itinerary

- apps/api/src/routes/api/activities-v2/services/default.ts
- apps/web/module/Listing/Activity/index.tsx
Fixed error on saving editing segments
> [Bug-Feature] Fix error on saving editing segments

- apps/web/module/Listing/Activity/CheckoutBox.tsx
Fixed error on Activity Box UI
> [Bug-Feature] Fixed error on Activity Box UI

- apps/web/module/Hosting/Listings/Properties/Property/Units/modals/SelectUnitTypeModal.tsx
Modified Create property unit modal
> [Story-Feature] Modify Create property unit modal

- apps/web/module/Hosting/Insights/index.tsx
- apps/web/module/Hosting/PaymentHistory/Graph.tsx
- apps/web/module/Hosting/PaymentHistory/GraphTab.tsx
- apps/web/module/Hosting/PaymentHistory/hooks/useGetFilteredPaymentHistory.tsx
> [ Story - Feature ] Change the bar graph of payment history to month by month

- apps/web/module/Hosting/Earnings/EarningGraphTab.tsx
- apps/web/module/Hosting/Earnings/components/YearToDateSummaryBox.tsx
> [Story-Feature] Added filter to earnings

- apps/api/src/routes/api/properties-v2/services/units.ts
- apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/Bed.tsx
- apps/web/module/Hosting/Listings/Properties/hooks/useUpdateBedBasicInfo.ts
- packages/contract/src/BookableUnitType/type.ts
- packages/contract/src/BookableUnitType/zod.ts
- packages/database/mongo/models/dbBookableUnitTypes.ts
Modify Add shared space/beds page ui
> [Story-Feature] Modify Add shared space/beds page ui

- apps/web/app/(guides)/guides/islands/page.tsx
- apps/web/module/Guides/Islands/index.tsx
Added getting to know island page
> [Task-Story] Getting to Know Island Page

- apps/web/common/components/SearchBar.tsx
- apps/web/common/components/SearchBar/ActivitiesSearchBar/index.tsx
- apps/web/common/components/SearchBar/PropertySearchBar/index.tsx
- apps/web/common/components/SearchBar/RentalsSearchBar/index.tsx
- apps/web/module/LandingPage/components/PropertySlider.tsx
- apps/web/module/LandingPage/components/Slider.tsx
- apps/web/module/LandingPage/index.tsx
Revamped search section for landing page
> [Task-Story] Create search section component for landing page

- apps/web/module/LandingPage/index.tsx
Connected guide pages to landing page
> [Story-Feature] Connected guide pages to landing page

- apps/api/src/routes/api/properties-v2/services/units.ts
- apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/WholePlace.tsx
- apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/components/AddBedroomModal.tsx
- apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/components/Bedroom.tsx
- apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/components/Photos.tsx
- apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/store/useBedroomStore.ts
- apps/web/module/Hosting/Listings/Properties/Property/Units/components/UnitsTable.tsx
- apps/web/module/Hosting/Listings/Properties/Property/Units/constants/index.ts
- apps/web/module/Hosting/Listings/Properties/Property/Units/index.tsx
- apps/web/module/Hosting/Listings/Properties/Property/Units/types/index.ts
- apps/web/module/Hosting/Listings/Properties/hooks/useUpdateWholePlaceBasicInfo.ts
- apps/web/package.json
- packages/database/mongo/models/dbBookableUnitTypes.ts
- pnpm-lock.yaml
> [ Feature ] Modify Add whole place page ui

- apps/api/src/routes/api/properties-v2/services/units.ts
- apps/web/module/Hosting/Listings/Properties/Property/Units/components/UnitsTable.tsx
- packages/database/mongo/models/dbBookableUnitTypes.ts
Removed description to units list, table, model and backend in units.ts
> [Story-Feature] Removed description to units list

- apps/web/module/BlogGuide/Guide/SurfingGuide/Directions.tsx
- apps/web/module/Guides/components/GuideContent.tsx
> [ Story - Feature ] Make the guide map square

- apps/api/src/routes/api/properties-v2/services/units.ts
- apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/Bed.tsx
- packages/contract/src/BookableUnitType/zod.ts
Added quantity input to shared room and connected it to the database.
> [Story-Feature] Added quantity to shared room

- apps/web/common/components/Filters/Minimap.tsx
Create reusable minimap search ui
> [Story-Feature] Create reusable minimap search ui

- apps/api/src/routes/api/rentals-v2/services/basicInfo.ts
- apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/components/AddBedroomModal.tsx
- apps/web/module/Hosting/Listings/Rentals/Rental/BasicInfo/index.tsx
- packages/contract/src/Rental/zod.ts
Add qty to rentals motorcycle and bikes UI and backend
> [Story-Feature] Add qty to rentals motorcycle and bikes UI and backend

- apps/web/common/components/Footer/index.tsx
- apps/web/common/components/Header.tsx
- apps/web/common/components/SearchBar.tsx
- apps/web/common/components/SearchBar/RentalsSearchBar/index.tsx
- apps/web/module/LandingPage/components/ImageTextCard.tsx
- apps/web/module/LandingPage/index.tsx
Rental Search pick up and drop date
> [Story-Feature] Rental Search pick up and drop date

- apps/web/common/components/Filters/CheckBoxFilter/index.tsx
- apps/web/module/LandingPage/components/Slider.tsx
- apps/web/module/LandingPage/components/SliderItem.tsx
- apps/web/module/LandingPage/components/TravelSlider.tsx
- apps/web/module/LandingPage/index.tsx
Created reusable slider item component and completed home page UI.
> [Task-Story] Complete home page UI

- apps/web/common/components/MultipleMarkerMap.tsx
- apps/web/common/components/SpecificMap.tsx
- apps/web/module/Accommodation/index.tsx
- apps/web/module/BlogGuide/Guide/SurfingGuide/Directions.tsx
- apps/web/module/BlogGuide/Guide/SurfingGuide/index.tsx
- apps/web/module/Guides/Islands/index.tsx
- apps/web/module/Guides/Restaurant/index.tsx
- apps/web/module/Guides/Surfing/index.tsx
- apps/web/module/Guides/components/GuideContent.tsx
- apps/web/module/Guides/data.json
> [ Story - Feature ] Put image name etc when hover on pin in guide map

- apps/web/common/components/Filters/BudgetFilter/BudgetSlider.tsx
- apps/web/common/components/Filters/CheckBoxFilter/index.tsx
- apps/web/common/components/Filters/Minimap.tsx
- apps/web/common/components/Filters/NumericFilter/index.tsx
- apps/web/common/components/Filters/SideFilter.tsx
- apps/web/module/LandingPage/components/TravelSlider.tsx
Create side filter reusable component
> [Story-Feature] Create side filter reusable component

- apps/web/common/components/MultipleMarkerMap.tsx
- apps/web/module/Guides/Restaurant/index.tsx
- apps/web/module/Guides/Surfing/index.tsx
- apps/web/module/Guides/components/GuideContent.tsx
Added level and cuisine to popup on guide map
> [Task-Story] Added level and cuisine to popup on guide map

- apps/web/module/LandingPage/components/Slider.tsx
- apps/web/module/LandingPage/components/SliderItem.tsx
- apps/web/module/LandingPage/components/TravelSlider.tsx
- apps/web/module/LandingPage/index.tsx
Changed link and url behaviour of SliderItem
> [Task-Story] Changed link and url behaviour of SliderItem

- apps/web/module/LandingPage/components/Slider.tsx
- apps/web/module/LandingPage/components/TravelSlider.tsx
- apps/web/module/LandingPage/index.tsx
Modified slider to accept how many items will display
> [Task-feature] Modified slider to accept how many items will display

- apps/api/src/routes/api/rentals-v2/index.ts
- apps/api/src/routes/api/rentals-v2/services/basicInfo.ts
- apps/api/src/routes/api/rentals-v2/services/calendar.ts
- packages/database/mongo/models/dbRentals.ts
Added api endpoint for getting rental bike calendar view
> [Task-Story] Added api endpoint for getting rental bike calendar view

- apps/api/src/routes/api/rentals-v2/index.ts
- apps/api/src/routes/api/rentals-v2/services/calendar.ts
Added endpoint for calendar rental motorcycle
> [Task-Story] Added endpoint for calendar rental motorcycle

- apps/api/src/routes/api/rentals-v2/services/calendar.ts
- apps/web/module/Hosting/Reservations/Calendar/Activity/CalendarTable.tsx
- apps/web/module/Hosting/Reservations/Calendar/AddReservationModal/index.tsx
- apps/web/module/Hosting/Reservations/Calendar/Property/CalendarTable.tsx
- apps/web/module/Hosting/Reservations/Calendar/Rental/CalendarTable.tsx
- apps/web/module/Hosting/Reservations/Calendar/Rental/SampleData.json
- apps/web/module/Hosting/Reservations/Calendar/ReservationCalendarModal.tsx
- apps/web/module/Hosting/Reservations/Calendar/hooks/useGetCalendarMotor.ts
- apps/web/module/Hosting/Reservations/types/CalendarTable.d.ts
Implemented calendar reservation for motorcycle in frontend
> [Task - Story] Implemented calendar reservation for motorcycle in frontend

- apps/web/common/components/ui/Select.tsx
- apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/WholePlace.tsx
- apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/components/AddBedroomModal.tsx
- apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/components/Bedroom.tsx
> [ Story - Feature ] On studio type unit you cant add room more than one

- apps/web/app/(locations)/ClientHeroSection.tsx
- apps/web/common/components/SearchBar.tsx
- apps/web/module/LandingPage/components/TravelSlider.tsx
- apps/web/module/LandingPage/index.tsx
- apps/web/module/Listings/index.tsx
- apps/web/module/TravelStyle/components/TravelStyleContainer.tsx
- apps/web/module/TravelStyle/components/TravelStyleItem.tsx
- apps/web/module/TravelStyle/index.tsx
Connect main landing page to second page
> [Story-Feature] Connect main landing page to second page

- apps/web/module/Hosting/Reservations/Calendar/hooks/useGetCalendarBike.ts
- apps/web/module/Hosting/Reservations/Calendar/hooks/useGetCalendarMotor.ts
Added custom hooks for getting bike calendar reservation
> [Task-Story] Added custom hooks for getting bike calendar reservation

- apps/web/common/components/SliderImages.tsx
- apps/web/module/Accommodation/components/ImageGallery.tsx
> [ Story - Feature ] Lightbox image gallery

- apps/web/module/LandingPage/components/Slider.tsx
- apps/web/module/LandingPage/components/TravelSlider.tsx
- apps/web/module/LandingPage/index.tsx
> [ Story - Feature ] Landing page improvements

- apps/api/src/routes/api/rentals-v2/index.ts
- apps/api/src/routes/api/rentals-v2/services/basicInfo.ts
- apps/api/src/routes/api/rentals-v2/services/calendar.ts
- apps/web/module/Hosting/Listings/Rentals/Rental/BasicInfo/index.tsx
Added backend car calendar reservation endpoint
> [Task - Story] Added backend car calendar reservation endpoint

- apps/web/app/(listings)/layout.tsx
- apps/web/common/components/SearchBar.tsx
- apps/web/common/components/SearchBar/ActivitiesSearchBar/index.tsx
- apps/web/common/components/SearchBar/PropertySearchBar/index.tsx
- apps/web/common/components/SearchBar/RentalsSearchBar/index.tsx
- apps/web/module/Listings/index.tsx
> [Task-Story] All content same margin including search bar

- apps/web/module/Hosting/Reservations/Calendar/hooks/useGetCalendarCar.ts
Added custom hook for getting cars calendar reservation
> feat(web): Added custom hook for getting cars calendar reservation

- apps/web/common/components/SliderImages.tsx
- apps/web/module/Accommodation/components/ImageGallery.tsx
Added Lightbox gallery to guides image gallery and on single page UI
> [Epic - Main] Added Lightbox gallery to guides image gallery and on single page UI

- apps/web/app/(listings)/layout.tsx
- apps/web/common/components/Filters/BudgetFilter/BudgetSlider.tsx
- apps/web/common/components/Filters/CheckBoxFilter/index.tsx
- apps/web/common/components/Filters/Minimap/index.tsx
- apps/web/common/components/Filters/NumericFilter/index.tsx
- apps/web/common/components/SearchBar.tsx
- apps/web/module/Listings/components/SideFilter.tsx
- apps/web/module/Listings/index.tsx
Some improvements in user interface with dynamic filter contents.
> [Task-Story] Edit side filter make it standout

- apps/web/app/(listings)/layout.tsx
- apps/web/common/components/Filters/BudgetFilter/BudgetSlider.tsx
- apps/web/common/components/Filters/CheckBoxFilter/index.tsx
- apps/web/common/components/Filters/Minimap/index.tsx
- apps/web/common/components/Filters/NumericFilter/index.tsx
- apps/web/common/components/SearchBar.tsx
- apps/web/common/components/SearchBar/ActivitiesSearchBar/index.tsx
- apps/web/common/components/SearchBar/PropertySearchBar/index.tsx
- apps/web/common/components/SearchBar/RentalsSearchBar/index.tsx
- apps/web/module/Listings/components/SideFilter.tsx
- apps/web/module/Listings/index.tsx
> [Story- Fature] Added dynamic side filters and changed column number of items

- apps/web/common/components/SearchBar.tsx
- apps/web/module/LandingPage/index.tsx
Continuation only. Link of landing page to second page. Search bar margin fixed in listings page.
> [Task-Story] Edit side filter make it standout 

- apps/web/module/Hosting/Listings/Rentals/Rental/Location/index.tsx
- apps/web/module/Hosting/Listings/hooks/useGetPropertyByHost.ts
- apps/web/module/Hosting/Listings/hooks/useGetPropertyById.ts
- apps/web/module/Hosting/Listings/hooks/useUpdatePropertyBasicInfo.ts
- apps/web/module/LandingPage/index.tsx
Fixed error on creating new property
> [Bug - Epic] Fixed error on creating new property

- CHANGELOG.md
- apps/web/module/Hosting/Earnings/EarningGraphTab.tsx
- apps/web/module/Hosting/Earnings/EarningsThisMonth.tsx
- apps/web/module/Hosting/Earnings/EarningsUpcoming.tsx
- apps/web/module/Hosting/Earnings/components/ThisMonthChart.tsx
- apps/web/module/Hosting/Earnings/components/UpcomingChart.tsx
- apps/web/module/Hosting/Listings/Rentals/Rental/Location/index.tsx
- apps/web/module/Hosting/Listings/hooks/useGetPropertyByHost.ts
- apps/web/module/Hosting/Listings/hooks/useGetPropertyById.ts
- apps/web/module/Hosting/Listings/hooks/useUpdatePropertyBasicInfo.ts
- apps/web/module/LandingPage/index.tsx
- package.json
> [Main to Epic] Sync Updates to Calendar Reservation from main

- CHANGELOG.md
- apps/web/module/Hosting/Earnings/EarningGraphTab.tsx
- apps/web/module/Hosting/Earnings/EarningsThisMonth.tsx
- apps/web/module/Hosting/Earnings/EarningsUpcoming.tsx
- apps/web/module/Hosting/Earnings/components/ThisMonthChart.tsx
- apps/web/module/Hosting/Earnings/components/UpcomingChart.tsx
- apps/web/module/Hosting/Listings/Rentals/Rental/Location/index.tsx
- apps/web/module/Hosting/Listings/hooks/useGetPropertyByHost.ts
- apps/web/module/Hosting/Listings/hooks/useGetPropertyById.ts
- apps/web/module/Hosting/Listings/hooks/useUpdatePropertyBasicInfo.ts
- apps/web/module/LandingPage/index.tsx
- package.json
> [Epic - Story] Sync updates from parent branch to child branch

- .github/workflows/deploy-home-manual.yml
- .github/workflows/deploy-home.yml
> [Hotifx] Update secrets in deploy-home workflows

- apps/web/app/(listings)/layout.tsx
- apps/web/common/components/Header.tsx
- apps/web/common/components/SearchBar/SearchBarNoHero.tsx
- apps/web/module/LandingPage/components/Slider.tsx
- apps/web/module/LandingPage/components/TravelSlider.tsx
- apps/web/module/LandingPage/index.tsx
Re-aligned margins of landing page contents and added new search bar without hero section for second page.
> [Task-Story] Landing and 2nd page UI Adjustments

- apps/web/common/components/SliderImages.tsx
- apps/web/module/Accommodation/components/ImageGallery.tsx
- apps/web/next.config.js
- pnpm-lock.yaml
Adjusted lightbox UI, put a text label in modal images and connected it to the database.
> [Story-Feature] Adjusted lightbox UI

- .github/workflows/deploy-home.yml
- docker/api/Dockerfile
- docker/cms/Dockerfile
- docker/cms/Dockerfile.arm
- docker/compose-arm-sit.yml
- docker/compose-sit.yml
- turbo.json
> [Hotfix] Fix workflows deployment problem

- apps/web/module/BlogGuide/Guide/RestaurantGuide/RestaurantLocation.tsx
- apps/web/module/BlogGuide/Guide/RestaurantGuide/components/ChefsNote.tsx
- apps/web/module/BlogGuide/Guide/RestaurantGuide/index.tsx
- apps/web/next.config.js
Removed about section and changed social accounts to icons only
> [Task-Story] Guide restaurants UI adjustments

- apps/web/module/BlogGuide/Guide/TravelBlog/PopularGuides.tsx
- apps/web/module/BlogGuide/Guide/TravelBlog/index.tsx
> [Story-Feature] Adjusted travel UI

- .gitignore
- apps/api/src/routes/api/properties-v2/index.ts
- apps/api/src/routes/api/properties-v2/services/calendar.ts
- apps/api/src/routes/api/properties-v2/services/units.ts
- packages/database/mongo/models/dbBookableUnitTypes.ts
Added get room calendar reservations endpoints
> [Task-Story] Added get room calendar reservations endpoints

- release-please-config.json
> [Hotfix] Added release please config for custom title and section

- docs/local_database_setup.md
> [Test] Update local database setup instructions and remove test message

- apps/web/common/components/CustomSquareSlider.tsx
- apps/web/module/Listing/components/BoxContainer.tsx
> [ Story - Feature ] Make the listbox square shape

- apps/api/src/common/middleware/auth/isUserLoggedIn3.ts
- apps/api/src/routes/api/users-v2/services/personalInfo.ts
> [ Bug - Feature ] Savings of emergencycontact not working

- apps/api/src/routes/api/properties-v2/index.ts
- apps/api/src/routes/api/properties-v2/services/calendar.ts
- apps/api/src/routes/api/properties-v2/services/units.ts
Added endpoint for get calendar reservations for beds
> [Task - Story] Added endpoint for get calendar reservations for beds

- apps/api/src/routes/api/properties-v2/index.ts
- apps/api/src/routes/api/properties-v2/services/calendar.ts
> [ Story - Feature ] Create endpoint for calendar unit whole place reservations

- apps/web/module/Hosting/Reservations/Calendar/hooks/useGetCalendarBed.ts
Added custom hook for get calendar bed reservations
> [Task - Story] Added custom hook for get calendar bed reservations

- apps/web/module/Hosting/Reservations/Calendar/hooks/useGetCalendarWholePlace.ts
> [ Story - Feature ] Create custom hooks for get calendar unit whole place reservations

- apps/web/app/(blog-guide)/layout.tsx
- apps/web/common/components/SearchBar/ActivitiesSearchBar/index.tsx
- apps/web/common/components/SearchBar/PropertySearchBar/index.tsx
- apps/web/common/components/SearchBar/RentalsSearchBar/index.tsx
- apps/web/common/components/SearchBar/SearchBar.tsx
- apps/web/module/BlogGuide/Guide/TravelBlog/index.tsx
- apps/web/next.config.js
Added search bar in surf guide.
> [Task-Story] Guides surf UI adjustments

- apps/web/app/(blog-guide)/layout.tsx
- apps/web/app/(listings)/layout.tsx
- apps/web/common/components/Header.tsx
- apps/web/common/components/SearchBar/ActivitiesSearchBar/index.tsx
- apps/web/common/components/SearchBar/PropertySearchBar/index.tsx
- apps/web/common/components/SearchBar/RentalsSearchBar/index.tsx
- apps/web/common/components/SearchBar/SearchBar.tsx
- apps/web/common/components/SearchBar/SearchBarNoHero.tsx
- apps/web/common/components/SliderImages.tsx
- apps/web/module/Accommodation/components/ImageGallery.tsx
- apps/web/module/BlogGuide/Guide/RestaurantGuide/RestaurantLocation.tsx
- apps/web/module/BlogGuide/Guide/RestaurantGuide/components/ChefsNote.tsx
- apps/web/module/BlogGuide/Guide/RestaurantGuide/index.tsx
- apps/web/module/BlogGuide/Guide/TravelBlog/PopularGuides.tsx
- apps/web/module/BlogGuide/Guide/TravelBlog/index.tsx
- apps/web/module/LandingPage/components/Slider.tsx
- apps/web/module/LandingPage/components/TravelSlider.tsx
- apps/web/module/LandingPage/index.tsx
- apps/web/next.config.js
- pnpm-lock.yaml
Improved base from comments on 08-16-2024
> [Story - Epic] Improved base from comments on 08-16-2024

- apps/web/module/Hosting/Reservations/Calendar/Sidebar.tsx
- apps/web/module/Hosting/Reservations/components/CalendarTab.tsx
Created calendar tabs for rental and properties calendar.
> [Story-Feature] Create tabs for rental and properties calendar

- CHANGELOG.md
- apps/web/module/BlogGuide/Guide/RestaurantGuide/index.tsx
- apps/web/module/BlogGuide/Guide/SurfingGuide/index.tsx
- apps/web/module/BlogGuide/Guide/TravelBlog/index.tsx
Fixed fetch issue. Changed localhost URL to WEB_URL
> [Hotfix] Change to webURL all localhost url on guides pages

- apps/web/common/components/Header/LoggedInUserDropdown.tsx
- pnpm-lock.yaml
Added divider on user dropdown menu on header
> [Story-Feature] Added divider on user dropdown menu on header

- apps/api/src/routes/api/properties-v2/index.ts
- apps/api/src/routes/api/properties-v2/services/calendar.ts
> [ Story - Feature ] Backend get property calendars

- apps/web/module/Hosting/Reservations/Calendar/hooks/useGetCalendarProperty.ts
> [ Story - Feature ] Custom hooks for get property

- apps/api/src/routes/api/rentals-v2/index.ts
- apps/api/src/routes/api/rentals-v2/services/basicInfo.ts
- apps/api/src/routes/api/rentals-v2/services/calendar.ts
- apps/web/module/Hosting/Reservations/Calendar/Rental/BikeCalendarTable.tsx
- apps/web/module/Hosting/Reservations/Calendar/Rental/CarCalendarTable.tsx
- apps/web/module/Hosting/Reservations/Calendar/Rental/MotorCalendarTable.tsx
- apps/web/module/Hosting/Reservations/Calendar/hooks/useUpdateVehicleName.ts
- apps/web/module/Hosting/Reservations/types/CalendarTable.d.ts
- packages/database/mongo/models/dbRentals.ts
Created and implemented edit rental child name to frontend
> [ Feature - Epic] Created and implemented edit rental child name to frontend

- apps/web/module/Hosting/Reservations/Calendar/Activity/CalendarTable.tsx
- apps/web/module/Hosting/Reservations/Calendar/Activity/SampleData.json
- apps/web/module/Hosting/Reservations/Calendar/Activity/index.tsx
- apps/web/module/Hosting/Reservations/components/CalendarLegend.tsx
- apps/web/module/Hosting/Reservations/components/LegendModal.tsx
- apps/web/module/Hosting/Reservations/helpers/legends.ts
- apps/web/module/Hosting/Reservations/types/CalendarTable.d.ts
Added legends for reservation calendar.
> [Story-Feature] Legends for calendar priorities need to apply the initial ui

- apps/web/module/Hosting/Reservations/Calendar/Activity/CalendarTable.tsx
- apps/web/module/Hosting/Reservations/Calendar/Activity/SampleData.json
- apps/web/module/Hosting/Reservations/Calendar/Activity/index.tsx
- apps/web/module/Hosting/Reservations/Calendar/Property/BedReservationCalendar.tsx
- apps/web/module/Hosting/Reservations/Calendar/Property/CalendarTable.tsx
- apps/web/module/Hosting/Reservations/Calendar/Property/ReservationCalendar.tsx
- apps/web/module/Hosting/Reservations/Calendar/Property/RoomReservationCalendar.tsx.tsx
- apps/web/module/Hosting/Reservations/Calendar/Property/WholePlaceReservationCalendar.tsx
- apps/web/module/Hosting/Reservations/Calendar/Rental/BikeCalendarTable.tsx
- apps/web/module/Hosting/Reservations/Calendar/Rental/BikeReservationCalendar.tsx
- apps/web/module/Hosting/Reservations/Calendar/Rental/CarReservationCalendar.tsx
- apps/web/module/Hosting/Reservations/Calendar/Rental/MotorReservationCalendar.ts.tsx
- apps/web/module/Hosting/Reservations/Calendar/Sidebar.tsx
- apps/web/module/Hosting/Reservations/components/CalendarLegend.tsx
- apps/web/module/Hosting/Reservations/components/CalendarTab.tsx
- apps/web/module/Hosting/Reservations/components/LegendModal.tsx
- apps/web/module/Hosting/Reservations/components/ReservationTab.tsx
- apps/web/module/Hosting/Reservations/helpers/legends.ts
Added legends in property and rental calendar.
> [Story-Feature] Implement Legends to rental and properties

- apps/web/common/components/ui/Input.tsx
- apps/web/common/components/ui/Select.tsx
- apps/web/common/components/ui/Typography.tsx
- apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/WholePlace.tsx
Changed border radius of inputs to standard (rounded-xl)
> [Story-Feature] All inputs radius standard

- apps/web/module/Hosting/Listings/Activities/index.tsx
- apps/web/module/Hosting/Listings/Properties/index.tsx
Adjusted the code  to make sure that the pagination works on properties and activities tabs.
> [Story-Feature] adjusted listing units pagination to make the pagination work

- apps/web/module/Hosting/Listings/Activities/Activity/AdditionalInfo/index.tsx
- apps/web/module/Hosting/Listings/Activities/Activity/BasicInfo/index.tsx
- apps/web/module/Hosting/Listings/Activities/Activity/Inclusions/index.tsx
- apps/web/module/Hosting/Listings/Properties/Property/Pricing/PricingContent.tsx
- apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/Room.tsx
- apps/web/module/Hosting/Listings/Rentals/Rental/AddOns/index.tsx
- apps/web/module/Hosting/Listings/components/modals/EditPhotoModal.tsx
Changed inputs border radius from md to xl
> [FE] Fix all inputs radius to rounded-xl

- apps/web/common/components/Tabs.tsx
- apps/web/module/Hosting/Reservations/components/CalendarLegend.tsx
- apps/web/module/Hosting/Reservations/components/CalendarTab.tsx
Added expand legends text and dynamic hover in rental tabs
> [Story-Feature] Click to expand legends and rental calendar tabs

- packages/database/mongo/models/dbReservations.ts
> [Story - Main] Modified reservation db model

- apps/web/common/components/SpecificMap.tsx
- apps/web/module/Hosting/Listings/Activities/Activity/Itinerary/index.tsx
- apps/web/module/Hosting/Listings/Properties/Property/Location.tsx
- apps/web/module/Hosting/Listings/Rentals/Rental/Location/index.tsx
> [Feature-Main] Modify listing setup locations

- apps/api/src/routes/api/rentals/index.ts
- apps/api/src/routes/api/rentals/services/rentals.ts
Added endpoint for getting all ids in rental
> [Story - Main] Added endpoint for getting all ids in rental

- apps/api/src/routes/api/reservations/index.ts
- apps/api/src/routes/api/reservations/services/rentalReservation.ts
- apps/api/src/routes/index.ts
- packages/database/mongo/models/dbReservations.ts
Added endpoint for adding rental reservations
> [Story - Main] Added endpoint for adding rental reservations

- apps/web/module/Hosting/Reservations/Calendar/hooks/useAddRentalReservation.ts
Added custom hook for adding new rental reservation
> [Story - Main] Added custom hook for adding new rental reservation

- apps/web/module/Hosting/Reservations/Calendar/AddReservationModal/Rental/RentalSelectLegendForm/index.tsx
- apps/web/module/Hosting/Reservations/Calendar/AddReservationModal/Rental/index.tsx
- apps/web/module/Hosting/Reservations/Calendar/Rental/CarCalendarTable.tsx
> feat: Connect Add Rental Reservation Modal frontend to backend

- apps/web/module/Hosting/Reservations/Calendar/Rental/BikeCalendarTable.tsx
- apps/web/module/Hosting/Reservations/Calendar/Rental/CarCalendarTable.tsx
- apps/web/module/Hosting/Reservations/Calendar/Rental/MotorCalendarTable.tsx
- apps/web/module/Hosting/Reservations/helpers/legends.ts
> [Bugfix] Bug fix error not showing bar on previous dates

- apps/web/module/Authentication/components/LoginForm.tsx
> [Bugfix] After login login button still showing

- apps/api/src/routes/api/reservations/services/rentalReservation.ts
- apps/web/module/Hosting/Reservations/Calendar/AddReservationModal/Rental/RentalReservationForm/index.tsx
- apps/web/module/Hosting/Reservations/Calendar/hooks/useAddRentalReservation.ts
- packages/database/mongo/models/dbReservations.ts
> [Story-Main] Add notes field for add reservation modal in rental calendar

- apps/api/src/routes/api/reservations/services/rentalReservation.ts
- apps/web/module/Hosting/Reservations/Calendar/AddReservationModal/Rental/RentalReservationForm/index.tsx
- apps/web/module/Hosting/Reservations/Calendar/Rental/CarCalendarTable.tsx
- apps/web/module/Hosting/Reservations/helpers/legends.ts
- packages/database/mongo/models/dbReservations.ts
> [Story-Main] Add Guest name to blocked dates on add reservation modal in rental calendar

- apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/WholePlace.tsx
- apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/store/useUnitTypeStore.ts
- apps/web/module/Hosting/Listings/Properties/Property/Units/components/UnitsTable.tsx
- apps/web/module/Hosting/Listings/Properties/Property/Units/index.tsx
- apps/web/module/Hosting/Listings/Properties/Property/Units/modals/SelectUnitTypeWholePlaceModal.tsx
- apps/web/module/Hosting/Listings/Properties/index.tsx
- apps/web/next-env.d.ts
- packages/contract/src/Property/enum.ts
Modified logic of whole place unit
> [Story-Feature] Modified logic of whole place unit

- apps/web/module/Admin/Listings/ForReview/Property/Facilities/index.tsx
- apps/web/module/Hosting/Listings/Properties/Property/Facilities/index.tsx
Added descriptive text to Property Facilities
> [Story - Main] Added descriptive text to Property Facilities

- apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/Bed.tsx
> {Story-Main] Modified unit bed setup UI

- apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/Bed.tsx
- apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/Room.tsx
- apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/WholePlace.tsx
Descriptions and tags for photos made mandatory
> [Story-Feature] Descriptions and tags for photos made mandatory

- apps/web/module/Hosting/Reservations/Calendar/AddReservationModal/Rental/RentalReservationForm/index.tsx
- apps/web/module/Hosting/Reservations/Calendar/Rental/CarCalendarTable.tsx
- apps/web/module/Hosting/Reservations/Calendar/RentalCalendarModal/index.tsx
- apps/web/module/Hosting/Reservations/Calendar/ReservationCalendarModal.tsx
> [Story-Main] Show all datas on reservation modal in rental reservation calendar

- apps/web/module/Hosting/Listings/Activities/Activity/Itinerary/index.tsx
- apps/web/module/Hosting/Listings/Properties/Property/Location.tsx
- apps/web/module/Hosting/Listings/Rentals/Rental/Location/index.tsx
Modified Locations setup for all categories
> [Story - Feature] Modified Locations setup for all categories

- apps/api/src/routes/api/rentals/services/calendar.ts
- apps/api/src/routes/api/reservations/index.ts
- apps/api/src/routes/api/reservations/services/rentalReservation.ts
Added endpoint for modifying rental reservation
> [Story - Main] Added endpoint for modifying rental reservation

- apps/web/module/Hosting/Reservations/Calendar/AddReservationModal/Property/PropertyReservationForm/index.tsx
- apps/web/module/Hosting/Reservations/Calendar/AddReservationModal/Property/PropertylSelectLegendForm/index.tsx
- apps/web/module/Hosting/Reservations/Calendar/AddReservationModal/Property/index.tsx
- apps/web/module/Hosting/Reservations/Calendar/Property/CalendarTable.tsx
> [Story-Main] Create Add Property reservation modal

- apps/api/src/routes/api/reservations/services/rentalReservation.ts
- apps/web/module/Hosting/Reservations/Calendar/Rental/CarCalendarTable.tsx
- apps/web/module/Hosting/Reservations/Calendar/RentalCalendarModal/index.tsx
- apps/web/module/Hosting/Reservations/Calendar/ReservationCalendarModal.tsx
- apps/web/module/Hosting/Reservations/Calendar/hooks/useUpdateRentalReservation.ts
- apps/web/module/Hosting/Reservations/types/CalendarTable.d.ts
> [Story-Main] Connect Edit rental reservation modal to backend

- apps/api/src/routes/api/properties/services/calendar.ts
- apps/api/src/routes/api/reservations/index.ts
- apps/api/src/routes/api/reservations/services/unitsReservation.ts
Added add unit reservation endpoint
> [Stpry- Main] Added add unit reservation endpoint

- apps/api/src/routes/api/properties/services/units.ts
- apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/Room.tsx
- apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/components/AddBedroomModal.tsx
- apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/components/Bedroom.tsx
- apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/store/useBedroomStore.ts
- apps/web/module/Hosting/Listings/Properties/Property/Units/components/UnitsTable.tsx
- apps/web/module/Hosting/Listings/Properties/hooks/useUpdateRoomBasicInfo.ts
> [Story-Feature] Modified inputs of room units

- CHANGELOG.md
- apps/api/src/routes/api/properties/index.ts
- apps/api/src/routes/api/properties/services/calendar.ts
- apps/api/src/routes/api/properties/services/units.ts
- apps/web/module/Hosting/Reservations/Calendar/AddReservationModal/Property/PropertyReservationForm/index.tsx
- apps/web/module/Hosting/Reservations/Calendar/AddReservationModal/Property/hooks/useAddPropertyReservation.ts
- apps/web/module/Hosting/Reservations/Calendar/AddReservationModal/Property/hooks/useGetUnitById.ts
- apps/web/module/Hosting/Reservations/Calendar/AddReservationModal/Property/index.tsx
- apps/web/module/Hosting/Reservations/Calendar/Property/CalendarTable.tsx
- packages/database/mongo/models/dbBookableUnitTypes.ts
> [Story-Main] Connect Add property reservation modal to backend

- .github/workflows/release-please.yml
> [Hotfix] Test release please changes 

- CHANGELOG.md
- apps/web/module/Hosting/Reservations/Calendar/Activity/index.tsx
- apps/web/module/Hosting/Reservations/Calendar/Property/BedReservationCalendar.tsx
- apps/web/module/Hosting/Reservations/Calendar/Property/ReservationCalendar.tsx
- apps/web/module/Hosting/Reservations/Calendar/Property/RoomReservationCalendar.tsx.tsx
- apps/web/module/Hosting/Reservations/Calendar/Property/WholePlaceReservationCalendar.tsx
- apps/web/module/Hosting/Reservations/Calendar/Rental/BikeReservationCalendar.tsx
- apps/web/module/Hosting/Reservations/Calendar/Rental/CarReservationCalendar.tsx
- apps/web/module/Hosting/Reservations/Calendar/Rental/MotorReservationCalendar.ts.tsx
- apps/web/next-env.d.ts
> [Story- Main] Removed Table view button

- apps/api/src/routes/api/properties/index.ts
- apps/api/src/routes/api/properties/services/default.ts
- apps/api/src/routes/api/properties/services/propertyType.ts
- apps/web/module/Hosting/Listings/Properties/Property/PropertyType.tsx
- apps/web/module/Hosting/Listings/Properties/hooks/useUpdateWholePlaceType.ts
- packages/database/mongo/models/dbProperties.ts
Added endpoint for updating whole place type
> [Story - Main]  Added endpoint for updating whole place type

- apps/web/module/Hosting/Reservations/Calendar/AddReservationModal/Rental/index.tsx
- apps/web/module/Hosting/Reservations/Calendar/Rental/MotorCalendarTable.tsx
- apps/web/module/Hosting/Reservations/Calendar/RentalCalendarModal/index.tsx
Added Edit and Add Motorcycle reservation modal
> [Story-Main] Added Edit and Add Motorcycle reservation modal

- apps/web/module/Hosting/Reservations/Calendar/AddReservationModal/Rental/index.tsx
- apps/web/module/Hosting/Reservations/Calendar/Rental/BikeCalendarTable.tsx
- apps/web/module/Hosting/Reservations/Calendar/RentalCalendarModal/index.tsx
Added Add and Edit Bike reservation modal
> feat(web): Added Add and Edit Bike reservation modal

- apps/api/src/routes/api/properties/services/calendar.ts
- apps/web/module/Hosting/Reservations/Calendar/Property/CalendarTable.tsx
- apps/web/module/Hosting/Reservations/Calendar/PropertyCalendarModal/index.tsx
- apps/web/module/Hosting/Reservations/types/CalendarTable.d.ts
Maked the edit unit reservation function work
> [Story - Main] Maked the edit unit reservation function work

- apps/web/module/Hosting/Reservations/Calendar/Property/CalendarTable.tsx
- apps/web/module/Hosting/Reservations/Calendar/Sidebar.tsx
- apps/web/module/Hosting/Reservations/Calendar/SidebarActionModals/MonthYearSelectorModal/index.tsx
- Instead of filtering the calendar using Month and Year, it was changed to Date
- Made the calendar show the current day in the fifth column instead of the first day of the month in the first column
> [Story-Main] Property Calendar calendar button function

- apps/web/module/Hosting/Reservations/Calendar/AddReservationModal/Property/PropertyReservationForm/index.tsx
- apps/web/module/Hosting/Reservations/Calendar/AddReservationModal/Rental/RentalReservationForm/index.tsx
- apps/web/module/Hosting/Reservations/Calendar/PropertyCalendarModal/index.tsx
- apps/web/module/Hosting/Reservations/Calendar/RentalCalendarModal/index.tsx
Added optional label for notes and fix some bugs on notes
> [Story-Main] Added optional label for notes and fix some bugs on notes

- apps/web/module/Hosting/Reservations/Calendar/Property/CalendarTable.tsx
- apps/web/module/Hosting/Reservations/Calendar/Rental/CarCalendarTable.tsx
> [Story-Main] Rental Calendar calendar button function

- apps/web/module/Hosting/Reservations/Calendar/Activity/CalendarTable.tsx
> [Story-Main] Activity Calendar calendar button function

- apps/api/src/routes/api/properties/services/units.ts
- apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/WholePlace.tsx
> [Bug - Main] Unit saving even if no photos or no amenities checked

- apps/web/module/Hosting/Reservations/Calendar/Sidebar.tsx
- apps/web/next-env.d.ts
Removed collapse button on all bookable category on calendar
> [Story - Main] Removed collapse button on all bookable category on calendar

- apps/web/module/Listing/Property/components/ImageGallery.tsx
- apps/web/module/Listing/Property/components/SectionInfo.tsx
Adjusted the height of public property page images. This is a story.
> [Story-Main] Adjusted the height of public property page images

- apps/web/module/Hosting/Reservations/Calendar/Property/CalendarTable.tsx
- apps/web/module/Hosting/Reservations/Calendar/Rental/BikeCalendarTable.tsx
- apps/web/module/Hosting/Reservations/Calendar/Rental/CarCalendarTable.tsx
- apps/web/module/Hosting/Reservations/Calendar/Rental/MotorCalendarTable.tsx
> [Story-Main] Calendar UI correction

- CHANGELOG.md
- apps/api/src/routes/api/activities/services/basic-info.ts
- apps/api/src/routes/api/activities/services/default.ts
- apps/web/module/Hosting/Listings/Activities/Activity/BasicInfo/index.tsx
- packages/contract/src/Activities/zod.ts
- packages/database/mongo/models/dbActivities.ts
Added activityType field on actvitiy model
> [Story-Main] Added activityType field on actvitiy model

- CHANGELOG.md
- apps/web/module/Hosting/Reservations/Calendar/Property/CalendarTable.tsx
- apps/web/module/Hosting/Reservations/Calendar/Rental/BikeCalendarTable.tsx
- apps/web/module/Hosting/Reservations/Calendar/Rental/CarCalendarTable.tsx
- apps/web/module/Hosting/Reservations/Calendar/Rental/MotorCalendarTable.tsx
> [Story - Main] Calendar counts available units automatic change depends on available units

- apps/web/module/Hosting/Listings/Activities/Activity/BasicInfo/index.tsx
> [Story-Main] Add Activity Type input in activity basic info setup

- apps/web/module/Hosting/Reservations/Calendar/Activity/index.tsx
- apps/web/module/Hosting/Reservations/Calendar/Rental/BikeReservationCalendar.tsx
- apps/web/module/Hosting/Reservations/Calendar/Rental/CarReservationCalendar.tsx
- apps/web/module/Hosting/Reservations/Calendar/Rental/MotorReservationCalendar.ts.tsx
- apps/web/module/Hosting/Reservations/components/ActivityCalendarLegend.tsx
- apps/web/module/Hosting/Reservations/components/ActivityLegendModal.tsx
- apps/web/module/Hosting/Reservations/components/RentalCalendarLegend.tsx
- apps/web/module/Hosting/Reservations/components/RentalLegendModal.tsx
- apps/web/module/Hosting/Reservations/helpers/activitylegends.ts
- apps/web/module/Hosting/Reservations/helpers/rentallegends.ts
> [Story-Main] Modified calendar legends

- CHANGELOG.md
- apps/api/src/routes/api/properties/services/default.ts
- apps/api/src/routes/api/properties/services/facilities.ts
- apps/api/src/routes/api/properties/services/policies.ts
- apps/web/app/(admin-listing-acco)/admin/listings/properties/[listingId]/property-type/page.tsx
- apps/web/app/(listing-property)/hosting/listings/properties/[listingId]/whole-place-type/page.tsx
- apps/web/app/(new-listing-property)/hosting/listings/properties/setup/[listingId]/whole-place-type/page.tsx
- apps/web/common/components/HostLayout/ListingSidebar/EditSidebar.tsx
- apps/web/common/components/HostLayout/ListingSidebar/SetupSidebar.tsx
- apps/web/common/components/HostLayout/ListingSidebar/links/edit.tsx
- apps/web/common/components/HostLayout/ListingSidebar/links/setup.tsx
- apps/web/module/Hosting/Listings/Properties/Property/Summary/index.tsx
- apps/web/module/Hosting/Listings/Properties/Property/WholePlaceType/constants/index.ts
- apps/web/module/Hosting/Listings/Properties/Property/WholePlaceType/index.tsx
> [Story - Main] Modify the process of setup for property whole place

- apps/web/module/Hosting/Reservations/Calendar/Rental/CarCalendarTable.tsx
- apps/web/module/Hosting/Reservations/Calendar/Sidebar.tsx
- apps/web/module/Hosting/Reservations/Calendar/SidebarActionModals/MonthYearSelectorModal/index.tsx
- apps/web/module/Hosting/Reservations/components/CalendarTab.tsx
> [Bug-Main] Rental cancelling calendar button not displaying the reservation blocks

- apps/web/module/Hosting/Listings/Properties/Property/BasicInfo/index.tsx
- apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/WholePlace.tsx
- apps/web/module/Hosting/Listings/Properties/Property/Units/components/UnitsTable.tsx
- apps/web/module/Hosting/Listings/Properties/Property/Units/index.tsx
- apps/web/module/Hosting/Listings/Properties/Property/Units/modals/SelectUnitTypeWholePlaceModal.tsx
- apps/web/module/Hosting/Listings/Properties/Property/WholePlaceType/index.tsx
- apps/web/module/Hosting/Listings/Properties/Property/WholePlaceType/store/useWholePlaceTypeSelectedStore.ts
- apps/web/module/Hosting/Listings/Properties/index.tsx
Removed the whole place modal in the process
> [Story-Main] Removed the whole place modal in the process

- CHANGELOG.md
- apps/web/module/Hosting/Reservations/Calendar/Sidebar.tsx
- apps/web/module/Hosting/Reservations/Calendar/SidebarActionModals/SideBarSearchModals/PropertySearchCalendar.tsx
> [Story-Main] Created calendar search modal

- apps/api/src/routes/api/activities/services/basic-info.ts
- packages/contract/src/Activities/zod.ts
- packages/database/mongo/models/dbActivities.ts
Modified activity model added experienceType field
> [Story - Main] Modified activity model added experienceType field

- apps/api/src/routes/api/properties/index.ts
- apps/api/src/routes/api/properties/services/calendar.ts
Added endpoint for adding price per dates on units
> [Story-Main] Added endpoint for adding price per dates on units

- apps/web/module/Hosting/Reservations/helpers/activitylegends.ts
- apps/web/module/Hosting/Reservations/helpers/legends.ts
- apps/web/module/Hosting/Reservations/helpers/rentallegends.ts
> [Story-Main] Change backgound color for hovering checkout, drop off and completed bar

- apps/web/module/Listing/Property/components/ImageGallery.tsx
- apps/web/module/Listing/Property/components/Map.tsx
- apps/web/module/Listing/Property/components/WhereYouWillBe.tsx
Added height for image box in public listing page
> Added more height for image box in public listing page

- apps/web/module/Hosting/Reservations/Calendar/Property/CalendarTable.tsx
- apps/web/module/Hosting/Reservations/Calendar/PropertyCalendarModal/index.tsx
- apps/web/module/Hosting/Reservations/Calendar/Rental/BikeCalendarTable.tsx
- apps/web/module/Hosting/Reservations/Calendar/Rental/CarCalendarTable.tsx
- apps/web/module/Hosting/Reservations/Calendar/Rental/MotorCalendarTable.tsx
Fixed the not match dates of reservation blocks on the calendar dates
> Fixed the not match dates of reservation blocks on the calendar dates

- CHANGELOG.md
- packages/database/mongo/models/dbActivities.ts
Modified activities model for activity type field
>  Modified activities model for activity type field

- apps/web/module/Hosting/Reservations/Calendar/Sidebar.tsx
Hide search button on calendar
> Hide search button on calendar

- CHANGELOG.md
- apps/web/module/Hosting/Reservations/Calendar/Activity/index.tsx
- apps/web/module/Hosting/Reservations/Calendar/Property/CalendarTable.tsx
- apps/web/module/Hosting/Reservations/Calendar/Property/ReservationCalendar.tsx
- apps/web/module/Hosting/Reservations/Calendar/Rental/CarReservationCalendar.tsx
- apps/web/module/Hosting/Reservations/components/ActivityCalendarLegend.tsx
Created text descriptions for no bookableunits in calendar
> Created text descriptions for no bookableunits in calendar

- apps/api/src/routes/api/rentals/services/calendar.ts
- apps/web/module/Hosting/Reservations/Calendar/Rental/BikeCalendarTable.tsx
- apps/web/module/Hosting/Reservations/Calendar/Rental/CarCalendarTable.tsx
- apps/web/module/Hosting/Reservations/Calendar/Rental/MotorCalendarTable.tsx
- apps/web/module/Hosting/Reservations/types/CalendarTable.d.ts
Display dynamic price on rental calendar
> Display dynamic price on rental calendar

- apps/api/src/routes/api/properties/services/calendar.ts
- apps/web/module/Hosting/Reservations/Calendar/Property/CalendarTable.tsx
> feat(web): Modify calendar side items property ui

- apps/api/src/routes/api/properties/services/calendar.ts
> [Bug-Main] Bug on adding reservation on property multiple display

- apps/web/module/Hosting/Reservations/Calendar/Property/CalendarTable.tsx
- apps/web/module/Hosting/Reservations/Calendar/Rental/BikeCalendarTable.tsx
- apps/web/module/Hosting/Reservations/Calendar/Rental/CarCalendarTable.tsx
- apps/web/module/Hosting/Reservations/Calendar/Rental/MotorCalendarTable.tsx
> feat(web): Correct the alignment on left of blocksbars on calendar

- apps/web/common/components/HostLayout/ListingSidebar/SetupSidebar.tsx
- apps/web/module/Hosting/Listings/Activities/Activity/BasicInfo/index.tsx
- packages/contract/src/Activities/zod.ts
Modified activity setup basic info ui
> Modified activity setup basic info ui

- apps/api/src/routes/api/properties/services/units.ts
- apps/api/src/routes/api/rentals/services/basicInfo.ts
- apps/api/src/routes/api/rentals/services/default.ts
- packages/contract/src/Rental/zod.ts
- packages/database/mongo/models/dbBookableUnitTypes.ts
- packages/database/mongo/models/dbRentals.ts
- packages/database/mongo/models/dbReservations.ts
Adjusted database model reservation units and rental
> Adjusted database model reservation units and rental

- apps/web/module/Hosting/Reservations/Calendar/Property/CalendarTable.tsx
- apps/web/module/Hosting/Reservations/Calendar/Rental/BikeCalendarTable.tsx
- apps/web/module/Hosting/Reservations/Calendar/Rental/CarCalendarTable.tsx
- apps/web/module/Hosting/Reservations/Calendar/Rental/MotorCalendarTable.tsx
- apps/web/module/Hosting/Reservations/Calendar/Sidebar.tsx
- apps/web/module/Hosting/Reservations/Calendar/SidebarActionModals/SideBarSearchModals/PropertySearchCalendar.tsx
> Rental Calendar search button function

- apps/web/module/Hosting/Reservations/Calendar/Rental/RentalsEditPricePerDatesModal.tsx
- apps/web/module/Hosting/Reservations/Calendar/hooks/useUpdateRentalPricePerDate.ts
> Connect PricePerdates add modal of rental to backend

- apps/api/src/routes/api/properties/services/calendar.ts
- apps/web/module/Hosting/Reservations/Calendar/Property/CalendarTable.tsx
Added displays of price per dates on property calendar
> Added displays of price per dates on property calendar

- apps/api/src/routes/api/properties/services/units.ts
- apps/web/module/Hosting/Reservations/Calendar/Activity/ActivityEditPricePerDatesModal.tsx
- apps/web/module/Hosting/Reservations/Calendar/Property/PropertyEditPricePerDatesModal.tsx
- apps/web/module/Hosting/Reservations/Calendar/Rental/RentalsEditPricePerDatesModal.tsx
- apps/web/tsconfig.json
Removed not needed fields in edit price modal
> Removed not needed fields in edit price modal

- apps/api/src/routes/api/activities/services/additionalInfo.ts
- packages/database/mongo/models/dbActivities.ts
Modified activity model schema added schedule and time slots
> Modified activity model schema added schedule and time slots

- README.md
- apps/api/src/routes/api/properties/services/default.ts
- apps/web/module/Hosting/Listings/Properties/Property/Location.tsx
> [Feature-Main] After updating property locations sidebar location not turn to green

- apps/web/module/Hosting/Listings/Activities/Activity/Summary/index.tsx
- apps/web/module/Hosting/Listings/Properties/Property/Summary/index.tsx
> [Bugfix] Activity setup summary error on image UI

- README.md
- apps/api/src/routes/api/activities/index.ts
- apps/api/src/routes/api/activities/services/price-slots.ts
- packages/contract/src/Activities/zod.ts
- packages/database/mongo/models/dbActivities.ts
Added endpoint for edit and get slots price
> Added endpoint for edit and get slots price

- apps/web/common/components/HostLayout/ListingSidebar/SetupSidebar.tsx
- apps/web/module/Hosting/Listings/Properties/Property/Location.tsx
Fixed bug after saving property policies sidebar changing layout
> Fixed bug after saving property policies sidebar changing layout

- apps/api/src/routes/api/activities/index.ts
- apps/api/src/routes/api/activities/services/calendar.ts
- apps/api/src/routes/api/activities/services/price-slots.ts
- apps/web/module/Hosting/Listings/Activities/Activity/Pricing/index.tsx
> Activity add price per dates endpoint

- apps/api/src/routes/api/reservations/index.ts
- apps/api/src/routes/api/reservations/services/activityReservation.ts
> [Feature-Main] Create add activity calendar reservation

- apps/api/src/routes/api/activities/index.ts
- apps/api/src/routes/api/activities/services/default.ts
- apps/api/src/routes/api/rentals/services/calendar.ts
- apps/api/src/routes/api/reservations/index.ts
- apps/api/src/routes/api/reservations/services/rentalReservation.ts
Added endpoint for cancelling rental reservation and gettng activity counts
> Added endpoint for cancelling rental reservation and gettng activity counts

- apps/api/src/routes/api/reservations/index.ts
- apps/api/src/routes/api/reservations/services/rentalReservation.ts
- apps/web/module/Hosting/Reservations/Calendar/PropertyCalendarModal/index.tsx
- apps/web/module/Hosting/Reservations/Calendar/RentalCalendarModal/index.tsx
- apps/web/module/Hosting/Reservations/Calendar/hooks/useCancelRentalReservation.ts
Added cancel rental reservation function
> Added cancel rental reservation function

- apps/api/src/routes/api/reservations/services/activityReservation.ts
- apps/web/module/Hosting/Reservations/Calendar/AddReservationModal/Activity/ActivityReservationForm/index.tsx
- apps/web/module/Hosting/Reservations/Calendar/AddReservationModal/Activity/hooks/useAddActivityReservation.ts
- apps/web/module/Hosting/Reservations/Calendar/AddReservationModal/Activity/hooks/useGetActivityByHost.ts
- apps/web/module/Hosting/Reservations/Calendar/AddReservationModal/Activity/hooks/useGetActivityById.ts
- apps/web/module/Hosting/Reservations/Calendar/AddReservationModal/Activity/index.tsx
> [Feature-Main] Add activity calendar reservation function

- apps/api/src/routes/api/activities/services/calendar.ts
- apps/api/src/routes/api/activities/services/default.ts
- apps/api/src/routes/api/activities/services/price-slots.ts
- apps/api/src/routes/api/reservations/index.ts
- apps/api/src/routes/api/reservations/services/activityReservation.ts
- apps/web/module/Hosting/Listings/Activities/Activity/Pricing/index.tsx
- packages/contract/src/Activities/zod.ts
- packages/database/mongo/models/dbActivities.ts
- packages/database/mongo/models/dbReservations.ts
Modified activity and reservation model
> Modified activity and reservation model

- apps/api/src/routes/api/reservations/services/rentalReservation.ts
- apps/web/app/(host)/hosting/reservations/calendar/properties/page.tsx
Added logic allowed days to cancel  to rental cancel reservation endpoint
> Added logic allowed days to cancel  to rental cancel reservation endpoint

- apps/api/src/routes/api/reservations/index.ts
- apps/api/src/routes/api/reservations/services/activityReservation.ts
Added endpoint for adding joiner activity reservation
> Added endpoint for adding joiner activity reservation

- apps/api/src/routes/api/activities/services/price-slots.ts
- apps/api/src/routes/api/properties/services/calendar.ts
- apps/api/src/routes/api/properties/services/units.ts
- apps/api/src/routes/api/rentals/services/basicInfo.ts
- apps/api/src/routes/api/rentals/services/calendar.ts
- apps/api/src/routes/api/rentals/services/rentals.ts
- apps/api/src/routes/api/reservations/services/rentalReservation.ts
- apps/api/src/routes/api/reservations/services/unitsReservation.ts
- apps/web/module/Hosting/Reservations/Calendar/AddReservationModal/Rental/RentalReservationForm/index.tsx
- apps/web/module/Hosting/Reservations/Calendar/Property/modals/add-reservation-modal/property-reservation-form.tsx
- apps/web/module/Hosting/Reservations/Calendar/hooks/useAddRentalReservation.ts
- packages/database/mongo/models/dbActivities.ts
- packages/database/mongo/models/dbBookableUnitTypes.ts
- packages/database/mongo/models/dbRentals.ts
- packages/database/mongo/models/dbReservations.ts
…
Modified keys on property, renntal, activity and reservation model from ids to qtyIds
> Modified keys on property, renntal, activity and reservation model from ids to qtyIds

- apps/api/src/routes/api/activities/services/calendar.ts
Modified return of get joiner activities calendar
> Modified return of get joiner activities calendar

- apps/api/src/routes/api/reservations/index.ts
- apps/api/src/routes/api/reservations/services/unitsReservation.ts
- apps/web/module/Hosting/Reservations/Calendar/Property/modals/info-cancel-modal.tsx
- apps/web/module/Hosting/Reservations/Calendar/hooks/useCancelPropertyReservation.ts
Added Property cancellation function
> Added Property cancellation function

- apps/api/src/routes/api/activities/index.ts
- apps/api/src/routes/api/activities/services/calendar.ts
- packages/database/mongo/models/dbActivities.ts
Added endpoint for editing private activity slot note
> Added endpoint for editing private activity slot note

- apps/api/src/routes/api/activities/index.ts
- apps/api/src/routes/api/activities/services/calendar.ts
Added endpoint for editing slot name in joiner activities
> Added endpoint for editing slot name in joiner activities

- apps/api/src/routes/api/rentals/services/calendar.ts
…otorbike calendar
Fixed issue on not getting reservations on rental car and motorbike calendar
> Fixed issue on not getting reservations on rental car and motorbike calendar

- apps/api/src/routes/api/activities/services/calendar.ts
Fixed error on getting private activities with reservation
> Fixed error on getting private activities with reservation

- apps/web/module/Hosting/Reservations/Calendar/Property/calendar-table.tsx
- apps/web/module/Hosting/Reservations/Calendar/Property/controls.tsx
- apps/web/module/Hosting/Reservations/Calendar/SidebarActionModals/MonthYearSelectorModal/index.tsx
Fixed error on filter date function not working
> Fixed error on filter date function not working

- apps/web/module/Hosting/Listings/Properties/Property/Summary/index.tsx
Fixed bed units not showing and undefined values on summary
> Fixed bed units not showing and undefined values on summary

- apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/WholePlace.tsx
- apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/components/AddBedroomModal.tsx
- apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/components/Bedroom.tsx
- apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/components/Livingroom.tsx
Corrected label on bed room and living rooms when adding beds
> Corrected label on bed room and living rooms when adding beds

- apps/web/module/Hosting/Reservations/Calendar/activity/private-calendar-table/modals/add-reservation-modal/reservation-form.tsx
Fixed bug on adding private activity reservation
> Fixed bug on adding private activity reservation

- apps/api/src/routes/api/properties/services/unitPrice.ts
- apps/web/module/Hosting/Listings/Properties/Property/Pricing/PricingContent.tsx
- apps/web/module/Hosting/Listings/Properties/Property/Pricing/index.tsx
- apps/web/module/Hosting/Listings/Properties/Property/Units/components/UnitsTable.tsx
- apps/web/module/Hosting/Listings/Properties/Property/Units/constants/index.ts
Fixed bug bed unit not displaying correct name in listing process
> Fixed bug bed unit not displaying correct name in listing process

- apps/api/src/common/middleware/paginations/paginate.ts
- apps/api/src/routes/api/rentals/index.ts
- apps/api/src/routes/api/rentals/services/filtered.ts
Added get rentals by location and type with pagination that contain 15 items every page
> Added get rentals by location and type with pagination that contain 15 items every page

- apps/api/src/routes/api/activities/services/default.ts
- apps/web/common/constants/index.ts
- apps/web/module/Hosting/Listings/Activities/index.tsx
- apps/web/module/LandingPage/components/SliderItem.tsx
> Activity units liust fixed

- apps/api/src/routes/api/activities/index.ts
- apps/api/src/routes/api/activities/services/filtered.ts
- apps/api/src/routes/api/rentals/services/filtered.ts
Added endpoint for get activities by location and type with pagination
> Added endpoint for get activities by location and type with pagination

- apps/api/src/routes/api/reservations/services/activityReservation.ts
- apps/web/module/Hosting/Reservations/Calendar/activity/joiner-calendar-table/modals/add-reservation-modal/index.tsx
- apps/web/module/Hosting/Reservations/Calendar/activity/joiner-calendar-table/modals/add-reservation-modal/reservation-form.tsx
Changed logic for adding joiner activities reservation
> Changed logic for adding joiner activities reservation

- apps/api/src/routes/api/activities/services/filtered.ts
- apps/api/src/routes/api/properties/index.ts
- apps/api/src/routes/api/properties/services/filtered.ts
- apps/api/src/routes/api/rentals/services/filtered.ts
Added endpoint for getting properties by location and type
> Added endpoint for getting properties by location and type

- apps/api/src/routes/api/activities/services/calendar.ts
- apps/api/src/routes/api/reservations/services/activityReservation.ts
- apps/web/module/Hosting/Reservations/Calendar/activity/helpers/get-booking-style.ts
- apps/web/module/Hosting/Reservations/Calendar/activity/helpers/normalize-date.ts
- apps/web/module/Hosting/Reservations/Calendar/activity/joiner-calendar-table/index.tsx
- apps/web/module/Hosting/Reservations/Calendar/activity/private-activity.tsx
- apps/web/module/Hosting/Reservations/Calendar/activity/private-calendar-table/activity-unit-rows.tsx
- apps/web/module/Hosting/Reservations/Calendar/activity/private-calendar-table/index.tsx
Fixed activity reservation blocked color not changeing
> Fixed activity reservation blocked color not changeing

- apps/api/src/routes/api/rentals/index.ts
- apps/api/src/routes/api/rentals/services/filtered.ts
- apps/web/module/Hosting/Reservations/components/reservation-tab.tsx
Converted params to search query params and added more query params for filtering rentals
> Converted params to search query params and added more query params for filtering rentals

- apps/api/src/routes/api/activities/index.ts
- apps/api/src/routes/api/activities/services/filtered.ts
- apps/api/src/routes/api/rentals/services/filtered.ts
Converted params to query params and added more filter options in activities
> Converted params to query params and added more filter options in activities

- apps/api/src/routes/api/for-payment-listings/index.ts
- apps/api/src/routes/api/for-payment-listings/services/default.ts
- apps/api/src/routes/api/reservations/index.ts
- apps/api/src/routes/api/reservations/services/cart-reservations.ts
- apps/api/src/routes/api/reservations/services/default.ts
- apps/api/src/routes/api/reservations/services/for-payment-reservation.ts
- apps/api/src/routes/index.ts
- packages/contract-2/package.json
- packages/contract-2/src/for-payment-listings/for-payment.ts
- packages/contract-2/src/for-payment-listings/index.ts
- packages/contract-2/src/for-payment-listings/type.ts
- packages/contract-2/src/for-payment-listings/zod.ts
- packages/contract-2/src/reservations/reservation.ts
- packages/database/mongo/models/dbForPaymentListings.ts
- packages/database/mongo/models/dbReservations.ts
- packages/database/mongo/models/index.ts
Added endpoint for book now functions
> Added endpoint for book now functions

- apps/api/src/routes/api/activities/services/default.ts
- apps/api/src/routes/api/properties/services/default.ts
- apps/api/src/routes/api/rentals/services/default.ts
Added convertion of prices in all public page categories
> Added convertion of prices in all public page categories

- apps/api/src/routes/api/carts/services/default.ts
- apps/api/src/routes/api/for-payment-listings/services/default.ts
- packages/contract-2/src/for-payment-listings/zod.ts
- packages/database/mongo/models/dbForPaymentListings.ts
Adjusted for-payments and add computations
> Adjusted for-payments and add computations

- apps/api/src/routes/api/reservations/helpers/totalPrice.ts
- apps/api/src/routes/api/reservations/services/cart-reservations.ts
- apps/api/src/routes/api/reservations/services/for-payment-reservation.ts
- packages/contract-2/src/for-payment-listings/zod.ts
Modified the price base of total amount for all payments reservations
> Modified the price base of total amount for all payments reservations

- apps/api/src/routes/api/properties/services/default.ts
When changing property types reset units list on that property fixed
> When changing property types reset units list on that property fixed

- apps/api/src/routes/api/properties/services/filtered.ts
Modified property filter endpoint
> Modified property filter endpoint

- apps/api/src/routes/api/activities/services/filtered.ts
Fixed error on searching activity with numberOfGuest
> Fixed error on searching activity with numberOfGuest

- apps/api/src/routes/api/properties/services/default.ts
Reset all data when changing property type
> Reset all data when changing property type

- apps/api/src/routes/api/reservations/services/cart-reservations.ts
- apps/web/module/cart/checkout/index.tsx
- apps/web/module/cart/hooks/use-add-gcash-payment.ts
- packages/contract-2/src/cart/zod.ts
> Created Gcash Checkout

- apps/api/src/routes/api/reservations/services/cart-reservations.ts
- apps/web/module/cart/checkout/index.tsx
- apps/web/module/cart/hooks/use-add-card-payment.ts
- apps/web/module/landing-page/index.tsx
- apps/web/next.config.js
- packages/contract-2/src/reservations/reservation.ts
- packages/services/src/hmac.ts
> Created Saved Card Checkout

- apps/api/src/routes/api/carts/services/default.ts
- apps/web/next.config.js
Added schedule to req body on update cart
> Added schedule to req body on update cart

- apps/api/src/routes/api/reservations/services/cart-reservations.ts
- apps/web/module/cart/checkout/index.tsx
- apps/web/module/cart/hooks/use-add-manual-card-payment.ts
- packages/contract-2/src/reservations/reservation.ts
> Checkout using manual card

- apps/web/module/Hosting/Listings/Properties/Property/PropertyType.tsx
- apps/web/module/Hosting/Listings/Properties/modals/property-type-change-modal.tsx
added PropertyTypeChangeModal and update handlesave logic
> feat(web): added PropertyTypeChangeModal and update handlesave logic

- apps/api/src/routes/api/reservations/index.ts
- apps/api/src/routes/api/reservations/services/grouped-reservations/index.ts
- apps/api/src/routes/api/reservations/services/grouped-reservations/pipelines/groupedReservationPipeline.ts
- apps/api/src/routes/api/reservations/services/guest-reservations/index.ts
- apps/api/src/routes/api/reservations/services/guest-reservations/pipelines/active-reservation.ts
- apps/api/src/routes/api/reservations/services/guest-reservations/pipelines/cancelled-reservation.ts
- apps/api/src/routes/api/reservations/services/guest-reservations/pipelines/finish-reservation.ts
- packages/contract-2/src/reservations/reservation.ts
- packages/contract-2/src/reservations/type.ts
- packages/contract-2/src/reservations/zod.ts
Added endpoint for grouped by xenditReferenceId reservations
> Added endpoint for grouped by xenditReferenceId reservations

- apps/web/module/cart/lists/activity-item.tsx
- apps/web/module/cart/lists/property-item.tsx
- apps/web/module/cart/lists/rental-item.tsx
added startDate time and endDate time
> added startDate time and endDate time

- apps/web/common/components/ui/Input.tsx
- apps/web/common/components/ui/Select.tsx
- apps/web/common/components/ui/phone-input.tsx
- apps/web/module/cart/checkout/components/phoneInput.tsx
- apps/web/module/cart/checkout/modals/add-guest-modal.tsx
- apps/web/module/cart/checkout/modals/edit-guest-modal.tsx
- apps/web/module/cart/checkout/more-info/activity/contacts.tsx
- apps/web/module/cart/checkout/more-info/rental/contacts.tsx
- apps/web/module/cart/checkout/more-info/rental/index.tsx
added country code dropdown
https://drive.google.com/file/d/1F8-tUPzzmbnxZPl2gQq6O07pd5WGeTuX/view?usp=sharing
> added country code dropdown

- apps/web/module/cart/lists/activity-item.tsx
- apps/web/module/cart/modals/activity-guest-add-modal.tsx
- apps/web/module/cart/modals/update-activity-item-modal.tsx
- apps/web/module/cart/stores/use-activity-guests-store.ts
- packages/contract-2/src/cart/zod.ts
added update modal for activity categery
https://drive.google.com/file/d/180wsJbN93xmOuPJGLOHWk20OFl0MYBTh/view?usp=sharing
>  added update modal for activity categery

- apps/web/common/components/SearchBar/ActivitiesSearchBar/index.tsx
- apps/web/common/components/SearchBar/PropertySearchBar/index.tsx
- apps/web/common/components/SearchBar/guest-add-modal.tsx
added guestModal
(https://drive.google.com/file/d/11e0S3SLpRfY3WYvi-qy8uNfJNj82rEhx/view?usp=sharing)
>  added update guestModal for search guest

- apps/api/src/routes/api/activities/index.ts
- apps/api/src/routes/api/activities/services/filtered.ts
- apps/api/src/routes/api/activities/services/highest-price.ts
- apps/api/src/routes/api/activities/services/price-slots.ts
- packages/contract/src/Activities/zod.ts
- packages/seeder/src/activities-private.ts
fixed activities filtering endpoint and adjusted the pricePerPerson types
> fixed activities filtering endpoint and adjusted the pricePerPerson types

- apps/api/src/routes/api/wishlists/helpers/fn.ts
- apps/api/src/routes/api/wishlists/index.ts
- apps/api/src/routes/api/wishlists/services/default.ts
- apps/api/src/routes/index.ts
- packages/database/mongo/models/dbWishlists.ts
- packages/database/mongo/models/index.ts
added endpoint for adding wishlist and create database for wishlist
> added endpoint for adding wishlist and create database for wishlist

- apps/api/src/routes/api/wishlists/index.ts
- apps/api/src/routes/api/wishlists/services/default.ts
added endpoint for get all wishlist by category
> added endpoint for get all wishlist by category

- apps/web/common/components/AdminLayout/ListingActivityHeader.tsx
- apps/web/common/components/AdminLayout/ListingHeader.tsx
- apps/web/common/components/AdminLayout/ListingRentalHeader.tsx
- apps/web/common/components/HostLayout/Header.tsx
- apps/web/common/components/HostLayout/ListingHeader/index.tsx
- apps/web/module/Listing/modals/terms-and-conditions-modal.tsx
> Before creating a listing host need to agree in the tc

- apps/api/src/routes/api/wishlists/services/default.ts
- packages/contract-2/package.json
- packages/contract-2/src/wishlist/enum.ts
- packages/contract-2/src/wishlist/index.ts
- packages/contract-2/src/wishlist/type.ts
- packages/contract-2/src/wishlist/wishlist.ts
- packages/contract-2/src/wishlist/zod.ts
- packages/database/mongo/models/dbWishlists.ts
added endpoint for get wishlist per category
> added endpoint for get wishlist per category

- apps/web/module/cart/lists/index.tsx
> 1507 cart select all button is always selected

- packages/seeder/index.ts
- packages/seeder/src/wishlist.ts
> added seeder for wishlist

- apps/web/common/components/Header/WithSearch.tsx
- apps/web/common/components/SearchBar/SearchBarByStateWithHero.tsx
- apps/web/common/components/SearchBar/search-bar-by-state.tsx
- apps/web/module/Hosting/Listings/Activities/Activity/Pricing/index.tsx
- apps/web/module/search/activities/map/index.tsx
- apps/web/module/search/properties/map/index.tsx
- apps/web/module/search/rentals/map/index.tsx
> Header search on small screen in overflow to the right

- apps/web/common/components/custom-square-slider.tsx
> Fix error on image carousel on search filter results

- apps/web/module/Hosting/Listings/Activities/Activity/Pricing/index.tsx
> Update private activity setup on host to show price per person and price per slot input

- apps/api/src/common/helpers/capitalizedFirstLetter.ts
- apps/api/src/routes/api/host-approvals/index.ts
- apps/api/src/routes/api/host-approvals/services/default.ts
- packages/contract-2/src/host-approval/enum.ts
- packages/contract-2/src/host-approval/host-approval.ts
- packages/contract-2/src/host-approval/index.ts
- packages/contract-2/src/host-approval/type.ts
- packages/contract-2/src/host-approval/zod.ts
- packages/seeder/src/host-approval.ts
- packages/seeder/src/users.ts
added endpoint for gt all host approval by host
> added endpoint for gt all host approval by host

- apps/api/src/routes/api/host-approvals/index.ts
- apps/api/src/routes/api/host-approvals/services/default.ts
- packages/contract-2/src/host-approval/host-approval.ts
- packages/contract-2/src/host-approval/type.ts
- packages/contract-2/src/host-approval/zod.ts
added endpoint for updating host approval by host
> added endpoint for updating host approval by host

- apps/api/src/routes/api/host-approvals/index.ts
- apps/api/src/routes/api/host-approvals/services/default.ts
- packages/contract-2/src/host-approval/enum.ts
- packages/contract-2/src/host-approval/host-approval.ts
- packages/database/mongo/models/dbHostApproval.ts
added endpoint for cancellation of host approval request
> added endpoint for cancellation of host approval request

- apps/api/src/routes/api/host-approvals/index.ts
- apps/api/src/routes/api/host-approvals/services/default.ts
- packages/contract-2/src/host-approval/host-approval.ts
- packages/contract-2/src/host-approval/type.ts
- packages/contract-2/src/host-approval/zod.ts
added endpoint for get all approvals by admin and endpoint for approve or reject by admin
> added endpoint for get all approvals by admin and endpoint for approve or reject by admin

- apps/web/module/Listing/activity/checkout-box.tsx
- apps/web/module/cart/book-now/index.tsx
> Activity book now

- apps/web/module/Listing/Property/checkout-box.tsx
- apps/web/module/cart/book-now/index.tsx
\_Provide screenshots 
or short video to show that it is working (optional)
> Property book now

- apps/api/bruno/ES/bruno.json
- apps/api/bruno/ES/collection.bru
- apps/api/bruno/ES/environments/env.bru
- apps/api/bruno/ES/filters/get activities.bru
- apps/api/bruno/ES/filters/get property filters.bru
- apps/api/bruno/ES/filters/get rentals.bru
- apps/api/bruno/ES/login/login.bru
- apps/api/bruno/ES/wishlist/get wishlist.bru
- apps/api/src/routes/api/wishlists/index.ts
- apps/api/src/routes/api/wishlists/services/default.ts
- packages/contract-2/src/wishlist/type.ts
- packages/contract-2/src/wishlist/zod.ts
modified return of endpoint of get wishlist by category
> modified return of endpoint of get wishlist by category

- apps/api/bruno/ES/carts/Add to cart.bru
- apps/api/bruno/ES/carts/Get carts.bru
- apps/api/bruno/ES/carts/Update cart.bru
- apps/api/src/routes/api/users/index.ts
- apps/api/src/routes/api/users/services/auth.ts
- apps/web/module/Authentication/components/modals/OptMessageModal.tsx
- apps/web/module/Authentication/hooks/useSetReceivedEmail.ts
modified recieved-email endpoint
> modified recieved-email endpoint
